const questionBank = [
  {
    question: "IZ KOJE ZEMLJE DOLAZI ANIMIRANI LIK MEDVJEDIĆ PADDINGTON?",
    answers: ["PERUA", "KANADE", "INDIJE", "ISLANDA"]
  },
  {
  question: "POD KOJIM JE UMJETNIČKIM IMENOM POZNAT ANDRIJA VUJEVIĆ?",
  answers: ["ANDRIJA", "VUJA", "DJ ANDRE", "A.V. SOUND"]
},
{
  question: "KAKO SE ZOVE ČAROBNI MAČ KRALJA ARTURA?",
  answers: ["EXCALIBUR", "DURANDAL", "GRAM", "CALADBOLG"]
},
{
  question: "IZ KOJEG JE MJESTA PORIJEKLOM MARIJA MAGDALENA?",
  answers: ["MAGDALA", "NAZARET", "BETLEHEM", "JERUZALEM"]
},
{
  question: "KAKO SE U GRČKOJ MITOLOGIJI ZOVE BOŽICA LOVA, PRIRODE I MJESECA?",
  answers: ["ARTEMIDA", "ATENA", "HERA", "AFRODITA"]
},
{
  question: "KAKO SE U SLAVENSKOJ MITOLOGIJI ZOVE BOŽICA MLADOSTI I PROLJEĆA?",
  answers: ["VESNA", "MORANA", "LADA", "ŽIVA"]
},
{
  question: "KOJA MITSKA BIĆA JE SVAROG STVORIO KAO POSREDNIKE IZMEĐU LJUDI, HEROJA I BOGOVA?",
  answers: ["PATULJCI", "VILE", "ZMAJEVI", "DIVOVI"]
},
{
  question: "KAKO SE U STARORIMSKOJ MITOLOGIJI ZOVE BOŽICA LOVA, PRIRODE I MJESECA?",
  answers: ["DIANA", "VENUS", "MINERVA", "JUNO"]
},
{
  question: "KOJA SU PREOSTALA DVA JAHAČA APOKALIPSE UZ RAT I SMRT?",
  answers: ["GLAD I KUGA", "MRŽNJA I STRAH", "VATRA I LED", "TAMA I SVJETLO"]
},
{
  question: "KOJI JE MITSKI HEROJ UBIO MEDUZU?",
  answers: ["PERZEJ", "HERAKLO", "TEZEJ", "ODISEJ"]
},
{
  question: "KOJU JE BILJKU PITIA ŽVAKALA PRI PRORICANJU?",
  answers: ["LOVOR", "MASLINA", "VINOVA LOZA", "SMOKVA"]
},
{
  question: "KAKO SE NAZIVA JAPANSKA ZABAVA KOJU PREVODIMO KAO “PRAZNI ORKESTAR”?",
  answers: ["KARAOKE", "KABUKI", "BONSAI", "SUMO"]
},
{
  question: "KOLIKO JE KVADRATA DOSTA ZA SREĆU U PJESMI ALENA ISLAMOVIĆA?",
  answers: ["25", "50", "100", "12"]
},
{
  question: "KOJA JE AFRIČKA UDARALJKA SRODNA KSILOFONU?",
  answers: ["BALAFON", "BONGO", "DJEMBE", "CAJON"]
},
{
  question: "KOJE SE JOŠ VATRENO ORUŽJE SPOMINJE U PJESMI “ČAVOGLAVE” UZ KALAŠNJIKOV I THOMPSON?",
  answers: ["ZBROJEVKA", "GLOCK", "BERETTA", "MAUSER"]
},
{
  question: "KOJE JE SREDNJE IME ELVISA PRESLEYA?",
  answers: ["ARON", "JAMES", "LEE", "WAYNE"]
},
{
  question: "KAKO SE OD 1962. DO 1966. ZVAO SPLITSKI FESTIVAL?",
  answers: ["FESTIVAL ZABAVNE GLAZBE", "SPLIT SONG FEST", "DALMATINSKI FESTIVAL", "JADRANSKA MELODIJA"]
},
{
  question: "KAKO SE ZVAO GRAD MUMBAI PRIJE 1995. GODINE?",
  answers: ["BOMBAY", "CALCUTTA", "DELHI", "MADRAS"]
},
{
  question: "KOJI SU DIO TIJELA STARI RIMLJANI DRŽALI U RUCI PRI DAVANJU ZAKLETVE?",
  answers: ["TESTISE", "SRCE", "JEZIK", "RUKU"]
},
{
  question: "KOJE SU NACIONALNOSTI BILI ČLANOVI ORGANIZACIJE CRNI RUJAN?",
  answers: ["PALESTINCI", "LIBANONCI", "SIRIJCI", "EGIPĆANI"]
},
{
  question: "KOJI JE NAROD IZGRADIO PETRU U JORDANU?",
  answers: ["NABATEJCI", "FENIČANI", "SUMERANI", "ASIRCI"]
},
{
  question: "POD KOJIM JE IMENOM POZNAT NJEMAČKI BOMBARDER JUNKERS-87?",
  answers: ["STUKA", "MESSERSCHMITT", "LUFTWAFFE", "FALKE"]
},
{
  question: "KOJA JE DRŽAVA PROGLASILA UJEDINJENJE 1871. U VERSAILLESU?",
  answers: ["NJEMAČKA", "ITALIJA", "FRANCUSKA", "AUSTRIJA"]
},
{
  question: "KOJA AMERIČKA AUTOKOMPANIJA PROIZVODI MODEL CONTINENTAL?",
  answers: ["LINCOLN", "FORD", "CADILLAC", "CHEVROLET"]
},
{
  question: "KOJEM JE RODU AMERIČKE VOJSKE PRIPADAO LEE HARVEY OSWALD OD 1956. DO 1959.?",
  answers: ["MARINCI", "ZRAKOPLOVSTVO", "MORNARICA", "KOPNENA VOJSKA"]
},
{
  question: "ŠTO JE PO ZANIMANJU BIO SVETI PETAR PRIJE NEGO JE SREO ISUSA?",
  answers: ["RIBAR", "KOVAČ", "VOJNIK", "TRGOVAC"]
},
{
  question: "KOJEG JE GRADA PRINC PHILIP BIO VOJVODA?",
  answers: ["EDINBURGA", "LONDONA", "OXFORDA", "CAMBRIDGEA"]
},
{
  question: "KAKO SE ZOVE MLAĐI BRAT FIDELA CASTRA KOJI GA JE NASLIJEDIO NA ČELU KUBE?",
  answers: ["RAUL CASTRO", "CARLOS CASTRO", "MIGUEL CASTRO", "JORGE CASTRO"]
},
{
  question: "KAKO SE ZOVE ZATVOR KOD MÜNCHENA U KOJEM JE HITLER NAPISAO “MEIN KAMPF”?",
  answers: ["LANDSBERG", "DACHAU", "AUSCHWITZ", "BUCHENWALD"]
},
{
  question: "KOJI JE APOSTOL HODAO PO VODI PREMA ISUSU, ALI POČEO TONUTI?",
  answers: ["PETAR", "IVAN", "JAKOV", "ANDRIJA"]
},
{
  question: "KOJA JE SVETICA IZGOVORILA RIJEČI NA LOMAČI 1431. GODINE U ROUENU?",
  answers: ["IVANA ORLEANSKA", "SVETA KATARINA", "SVETA TEREZIJA", "SVETA ANA"]
},
{
  question: "KOJA JE EUROPSKA NACIJA PRVA OSNOVALA NASELJE NA MJESTU RIO DE JANEIRA?",
  answers: ["FRANCUZI", "PORTUGALCI", "ŠPANJOLCI", "ENGLEZI"]
},
{
  question: "ŠTO JE ZAPOČELO INVASIJOM BRODOVA SANTISIMA TRINIDAD, CABO SAN ANTONIO I SANTA FE?",
  answers: ["FALKLANDSKI RAT", "PRVI SVJETSKI RAT", "KUBANSKA KRIZA", "VIJETNAMSKI RAT"]
},
{
  question: "KOJA JE VALUTA UVEDENA U CRNOJ GORI 2006. GODINE?",
  answers: ["EURO", "DINAR", "KUNA", "MARKA"]
},
{
  question: "KOJI SU RAT ALBANCI ISKORISTILI ZA STJECANJE NEOVISNOSTI 1912.?",
  answers: ["BALKANSKI RAT", "PRVI SVJETSKI RAT", "KRIMSKI RAT", "NAPOLEONSKI RATOVI"]
},
{
  question: "KAKO SE NA LATINSKOM NAZIVA PAPINSKI PRSTEN?",
  answers: ["ANULUS PISCATORIS", "CORONA PAPALIS", "SCEPTRE ROMANUM", "SIGNUM DEI"]
},
{
  question: "KOJA JE DANAŠNJA DRŽAVA BILA POZNATA KAO ISTOČNI PAKISTAN?",
  answers: ["BANGLADEŠ", "SRI LANKA", "NEPAL", "MYANMAR"]
},
{
  question: "KOJI JE GLAZBENIK PRAVIM IMENOM VINCENT DAMON FURNIER?",
  answers: ["ALICE COOPER", "IGGY POP", "DAVID BOWIE", "OZZY OSBOURNE"]
},
{
  question: "KOJI POJAM POVEZUJE ROMAN MIROSLAVA KRLEŽE I PJESMU PARNOG VALJKA?",
  answers: ["GLEMBAYEVI", "ZASTAVE", "BANKET", "ARETAS"]
},
{
  question: "KOJI MARVELOV SUPERJUNAK DIJELI IME S PJESMOM NA ALBUMU “PARANOID” GRUPE BLACK SABBATH?",
  answers: ["IRON MAN", "THOR", "HULK", "SPIDER-MAN"]
},
{
  question: "U KOJEM JE HRVATSKOM GRADU ROĐENA JOSIPA LISAC?",
  answers: ["ZAGREB", "SPLIT", "RIJEKA", "OSIJEK"]
},
{
  question: "KOJA JE ŽIVOTINJA BILA U ORIGINALNOM NASLOVU PJESME “ZAŠTO PRAVIŠ SLONA OD MENE”?",
  answers: ["MIŠ", "PAS", "MAČKA", "PTICA"]
},
  {
    question: "KOJI ZNANSTVENIK JE OTKRIO DA JE LJUDSKI VID REZULTAT PROJEKCIJE NA MREŽNICI?",
    answers: ["JOHANNES KEPLER", "KOPERNIK", "ISAAC NEWTON", "GALILEO"]
  },
  {
    question: "KOLIKO DANA PO ISLAMSKOM KALENDARU IMA GODINA KOJA NIJE PRIJESTUPNA?",
    answers: ["354", "365", "376", "400"]
  },
  {
  question: "KOJA GLUMICA JE SVOJU NAJPOZNATIJU ULOGU OSTVARILA U SERIJI “FRIENDS” TUMAČEĆI ULOGU CHANDLEROVE DJEVOJKE JANICE?",
  answers: ["MAGGIE WHEELER", "JENNIFER ANISTON", "COURTENEY COX", "LISA KUDROW"]
},
{
  question: "ŽIVOT KOJEG GLAZBENIKA, ROĐENOG 1947., OBRAĐUJE FILM “ROCKETMAN” (2019.)?",
  answers: ["ELTON JOHN", "DAVID BOWIE", "FREDDIE MERCURY", "PAUL MCCARTNEY"]
},
{
  question: "ELENA BELOVA JE FIKTIVNI LIK IZ STRIPOVA I FILMOVA. POD KOJIM JE NADIMKOM PUNO POZNATIJA?",
  answers: ["BLACK WIDOW", "SCARLET WITCH", "CAPTAIN MARVEL", "WASP"]
},
{
  question: "U KOJEM SE TALIJANSKOM GRADU ODVIJA VEĆI DIO RADNJE FILMA “ČAJ SA MUSSOLINIJEM”?",
  answers: ["FIRENCA", "RIM", "MILANO", "NAPULJ"]
},
{
  question: "AKO JE NICOLAS CAGE U FILMU “FACE/OFF” (1997.) CASTOR TROY, TKO GLUMI SEANA ARCHERA?",
  answers: ["JOHN TRAVOLTA", "AL PACINO", "ROBERT DE NIRO", "BRUCE WILLIS"]
},
{
  question: "AKO SU U FILMU IZ 2001. GODINE GLAVNI MUŠKI LIKOVI MARK DARCY I DANIEL CLEAVER, KOJI GLAVNI ŽENSKI LIK NEDOSTAJE?",
  answers: ["BRIDGET JONES", "ANNA SCOTT", "JULIA ROBERTS", "SALLY ALBRIGHT"]
},
{
  question: "ZA KOJI JE FILM IZ 1995. EMIR KUSTURICA U CANNESU DOBIO DRUGU ZLATNU PALMU?",
  answers: ["UNDERGROUND", "CRNA MAČKA, BIJELI MAČOR", "DOM ZA VJEŠANJE", "OTAC NA SLUŽBENOM PUTU"]
},
{
  question: "KOJI HOROR FILM IZ 1982. GODINE, ČESTO POGREŠNO PRIPISIVAN STEVENU SPIELBERGU, JE ZAPRAVO REŽIRAO TOBE HOOPER?",
  answers: ["POLTERGEIST", "THE SHINING", "HALLOWEEN II", "THE THING"]
},
{
  question: "KAKO SE ZOVE TVRTKA JORDANA BELFORTA IZ FILMA “VUK SA WALL STREETA”?",
  answers: ["STRATTON OAKMONT", "WOLF CAPITAL", "STOCK KING LTD", "WALL STREET GROUP"]
},
{
  question: "ŠTO JE VECTOR UKRAO U FILMU “DESPICABLE ME” (2010.), ZBOG ČEGA GRU POŽELI UKRASTI MJESEC?",
  answers: ["PIRAMIDU IZ GIZE", "KIP SLOBODE", "EIFFELOV TORANJ", "VELIKI KANJON"]
},
{
  question: "KOJI JE PROSLAVLJENI GLAZBENIK RADIO GLAZBU ZA FILM “MAD MAX 3” (1985.)?",
  answers: ["MAURICE JARRE", "HANS ZIMMER", "ENNIO MORRICONE", "VANGELIS"]
},
{
  question: "KAKO SE PREZIVA LYDIA IZ FILMA “BEETLEJUICE”?",
  answers: ["DEETZ", "ADAMS", "BROWN", "TURNER"]
},
{
  question: "U KOJEM FILMU BRAD PITT GLUMI LIKA IMENA ALDO RAINE?",
  answers: ["INGLOURIOUS BASTERDS", "FIGHT CLUB", "SE7EN", "TROY"]
},
{
  question: "DR. HOUSE JE AMERIČKA MEDICINSKA DRAMSKA TV SERIJA. KAKO GLASI VLASTITO IME DOKTORA HOUSEA?",
  answers: ["GREGORY", "HENRY", "JAMES", "ROBERT"]
},
{
  question: "MIRA FURLAN JE NAJPOZNATIJA PO ULOZI U JEDNOJ KULTNOJ SF SERIJI. KAKO GLASI IME TE SERIJE?",
  answers: ["BABYLON 5", "STAR TREK", "STARGATE", "FIREFLY"]
},
{
  question: "U KOJEM JE GRADU SMJEŠTEN LEGENDARNI FIKTIVNI KAFIĆ “CHEERS”?",
  answers: ["BOSTON", "NEW YORK", "CHICAGO", "LOS ANGELES"]
},
{
  question: "KOJE SU DVIJE BOJE ODJEĆE PROFESORA BALTAZARA?",
  answers: ["CRVENA I PLAVA", "ZELENA I ŽUTA", "CRNA I BIJELA", "NARANČASTA I LJUBIČASTA"]
},
{
  question: "KAKO SE ZOVE STARIJI BRAT MICHAELA CORLEONEA KOJI STRADAVA U FILMU “KUM II”?",
  answers: ["FREDO", "SONNY", "CARLO", "VINCENT"]
},
{
  question: "KAKO SE ZOVE MANDRIL IZ FILMA “KRALJ LAVOVA” KOJI JE SAVJETNIK KRALJEVA?",
  answers: ["RAFIKI", "ZAZU", "TIMON", "PUMBAA"]
},
{
  question: "KAKO SE ZOVE MAJMUNSKI KRALJ U FILMU “KNJIGA O DŽUNGLI”?",
  answers: ["KING LOUIE", "BALOO", "SHERE KHAN", "KAA"]
},
{
  question: "KAKO SE ZOVE FILM IZ 1999. GODINE SMJEŠTEN U ZATVORU COLD MOUNTAIN PENITENTIARY?",
  answers: ["THE GREEN MILE", "SHAWSHANK REDEMPTION", "ESCAPE PLAN", "DEAD MAN WALKING"]
},
{
  question: "KAKO SE ZOVE MJESEC NA KOJEM SE ODVIJA RADNJA FILMA “AVATAR”?",
  answers: ["PANDORA", "TITAN", "EUROPA", "IO"]
},
{
  question: "KOJA JE ŽIVOTINJA POSLUŽILA KAO ZVUK ZA RAPTORE U FILMU “JURSKI PARK”?",
  answers: ["KORNJAČA", "ORAO", "VUK", "KONJ"]
},
{
  question: "KAKO SE ZOVE FIKTIVNI OTOČIĆ IZ SERIJE “SMRT U RAJU”?",
  answers: ["SAINT MARIE", "SAINT LUCIA", "BARBADOS", "GUADELOUPE"]
},
{
  question: "KAKO SE ZOVE PRVI FILM IZ SAGE “RATOVI ZVIJEZDA” IZ 1977. GODINE?",
  answers: ["A NEW HOPE", "THE EMPIRE STRIKES BACK", "RETURN OF THE JEDI", "THE PHANTOM MENACE"]
},
{
  question: "KAKO SE ZOVE HRVATSKI OMNIBUS FILM O “VJEČNOM DERBIJU”?",
  answers: ["ZG80", "METASTAZE", "SONJA I BIK", "KAUBOJI"]
},
{
  question: "KOJEG SU MARVELOVA SUPERJUNAKA GLUMILI ERIC BANNA, EDWARD NORTON I MARK RUFFALO?",
  answers: ["HULK", "IRON MAN", "THOR", "CAPTAIN AMERICA"]
},
{
  question: "KAKO SE ZOVE GLUMAC ČIJE SU POSLJEDNJE RIJEČI BILE ‘NIKAD NISAM TREBAO PRIJEĆI SA VISKIJA NA MARTINI’?",
  answers: ["HUMPHREY BOGART", "FRANK SINATRA", "MARLON BRANDO", "JAMES DEAN"]
},
{
  question: "KAKO SE ZOVE BIRTIA U FILMU “PULP FICTION” GDJE UMA THURMAN I JOHN TRAVOLTA PLEŠU?",
  answers: ["JACK RABBIT SLIM'S", "BIG KAHUNA", "RED APPLE DINER", "LOS POLLOS"]
},
{
  question: "KAKO SE ZOVE MAJSTOR KOJI JE IZRADIO PINOKIJA?",
  answers: ["GEPPETTO", "CARLO", "ANTONIO", "GIUSEPPE"]
},
{
  question: "U KOJOJ JE DRŽAVI SNIMLJEN FILM “DOBAR, LOŠ, ZAO” (1966.)?",
  answers: ["ŠPANJOLSKA", "ITALIJA", "SAD", "MEKSIKO"]
},
{
  question: "TKO JE REŽIRAO FILM “KING ARTHUR: LEGEND OF THE SWORD”?",
  answers: ["GUY RITCHIE", "RIDLEY SCOTT", "CHRISTOPHER NOLAN", "ZACK SNYDER"]
},
{
  question: "ŠTO U RUCI DRŽE VITO I MICHAEL CORLEONE U TRENUTCIMA SMRTI?",
  answers: ["NARANČU", "PIŠTOLJ", "KRUNU", "NOVAC"]
},
{
  question: "U KOJEM FILMU TARANTINO GLUMI PAPUČARA KOJI SE BOJI SUPRUGE BONNIE?",
  answers: ["PULP FICTION", "RESERVOIR DOGS", "KILL BILL", "DJANGO UNCHAINED"]
},
{
  question: "KAKO SE ZOVE CRNO-BIJELI FILM ZORANA TADIĆA IZ 1981. U KOJEM LIKOVI IMAJU ISTA IMENA KAO GLUMCI?",
  answers: ["RITAM ZLOČINA", "TREĆI KLJUČ", "OKUPACIJA U 26 SLIKA", "VARLJIVO LJETO"]
},
{
  question: "TKO U CRTIĆU TRAŽI BLAGO U ZEMLJI MINIMOYA?",
  answers: ["ARTHUR", "MERLIN", "ALADIN", "SIMBA"]
},
{
  question: "IGOR MEŠIN JE HRVATSKI GLUMAC KOJI JE IMAO ZAPAŽENU ULOGU U SERIJI “ODMORI SE, ZASLUŽIO SI”. KAKO SE ZOVE LIK KOJEG GLUMI?",
  answers: ["TIN KOSMIČKI", "BORIS KOSMIČKI", "ZLATKO KOSMIČKI", "IVAN KOSMIČKI"]
},
{
  question: "KAKO SE NAZIVA POJAM ZA TRI ILI VIŠE TONOVA KOJI ZAJEDNO ZVUČE SKLADNO?",
  answers: ["AKORD", "MELODIJA", "RITAM", "TEMPO"]
},
{
  question: "KOJI JE STANDARDNI SIMFONIJSKI ŽIČANI INSTRUMENT S NAJVEĆIM BROJEM ŽICA?",
  answers: ["HARFA", "VIOLINA", "VIOLONČELO", "KONTRABAS"]
},
{
  question: "KOLIKO ŽICA NAJČEŠĆE IMAJU GUSLE?",
  answers: ["1", "2", "3", "4"]
},
{
  question: "KAKO SE ZVAO GLAZBENI SASTAV CASS ELLIOT?",
  answers: ["THE MAMAS AND THE PAPAS", "THE SUPREMES", "THE SHIRELLES", "THE RONETTES"]
},
{
  question: "KAKO SE ZOVE NAJPOZNATIJI DETEKTIV AGATHE CHRISTIE KOJI SE POJAVLJUJE U ROMANU “ZLO POD SUNCEM”?",
  answers: ["HERCULE POIROT", "MISS MARPLE", "SHERLOCK HOLMES", "PHILIP MARLOWE"]
},
{
  question: "KOJA SE ŽIVOTINJA SPOMINJE U ZAGONETKI LUDOG KLOBUČARA U “ALISI U ZEMLJI ČUDESA”?",
  answers: ["GAVRAN", "SOVA", "VRABAC", "PAUN"]
},
{
  question: "KAKO SE PUNIM IMENOM ZOVE KRALJ PATULJAKA IZ ŽELJEZNOG GORJA U “HOBITU”?",
  answers: ["DAIN II IRONFOOT", "THORIN OAKENSHIELD", "BALIN", "GLOIN"]
},
{
  question: "KAKO SE ZOVE POGLAVIČINA KĆER U PRIČI “PETAR PAN”?",
  answers: ["TIGER LILY", "WENDY", "ALICE", "ARIEL"]
},
{
  question: "KAKO SE ZOVE ROMAN STEPHENA KINGA O OPASNOM PSU?",
  answers: ["CUJO", "IT", "MISERY", "CARRIE"]
},
{
  question: "TKO JE PJESNIK NA ČIJEM GROBU PIŠE “QUOTH THE RAVEN, ‘NEVERMORE’”?",
  answers: ["EDGAR ALLAN POE", "WALT WHITMAN", "ROBERT FROST", "T.S. ELIOT"]
},
{
  question: "U KOJEM RUSKOM GRADU ZAPOČINJE RADNJA ROMANA “RAT I MIR”?",
  answers: ["SANKT PETERBURG", "MOSKVA", "KAZAN", "NOVGOROD"]
},
{
  question: "PREZIME KOJEG JE FRANCUSKOG FIZIČARA U NASLOVU ROMANA UMBERTA ECA?",
  answers: ["FOUCAULT", "PASTEUR", "CURIE", "LAPLACE"]
},
{
  question: "TONY STARK (IRON MAN) U SVOM SE LABORATORIJU OSLANJA NA SUSTAV UMJETNE INTELIGENCIJE KOJI JE SAM OSMISLIO. KAKO SE TAJ SUSTAV ZOVE?",
  answers: ["JARVIS", "ULTRON", "FRIDAY", "VISION"]
},
  {
    question: "KOJA MJERNA JEDINICA JE DOBILA IME PO TALIJANSKOM PLEMIĆU?",
    answers: ["VOLT", "PASKAL", "OHM", "HERTZ"]
  },
  {
  question: "U KOJI JE GRAD SMJEŠTENA RADNJA ROMANA “MI DJECA S KOLODVORA ZOO”?",
  answers: ["BERLIN", "HAMBURG", "MUNCHEN", "FRANKFURT"]
},
{
  question: "KAKO SE ZOVE ANTAGONIST U “GOSPODARU PRSTENOVA” ČIJE OKO MOTRI S KULE?",
  answers: ["SAURON", "SARUMAN", "GOLLUM", "BALROG"]
},
{
  question: "KOJA IMENA STOJE IZA INICIJALA J.K. ROWLING?",
  answers: ["JOANNE KATHLEEN", "JULIA KAREN", "JESSICA KATE", "JANE KATHERINE"]
},
{
  question: "KOJI LIK FRANZA KAFKE NA SVOJ 30. ROĐENDAN UPADA U NEVOLJE?",
  answers: ["JOSEF K.", "GREGOR SAMSA", "KARL ROSSMANN", "FRANZ B."] 
},
{
  question: "U KOJOJ JE DRŽAVI SMJEŠTENA RADNJA ROMANA “MUŠKARCI KOJI MRZE ŽENE”?",
  answers: ["ŠVEDSKA", "NORVEŠKA", "DANSKA", "FINSKA"]
},
  {
    question: "KOLIKO JE KILOMETARA ZEMLJA UDALJENA OD SUNCA?",
    answers: ["148.23 MILIJUNA KM", "41.28 MILIJUNA KM", "14.82 MILIJUNA KM", "1.48 MILIJUNA KM"]
  },
  {
    question: "KOLIKO JE LJUDI DO SADA ŽIVJELO NA ZEMLJI?",
    answers: ["OKO 100 MILIJARDI", "OKO 5 BILIJUNA", "OKO 1 BILIJUN", "OKO 50 MILIJARDI"]
  },
  {
    question: "ŠTO JE BIO ČOVJEK NA KOJEM JE TEMELJEN LIK UJAK SAM?",
    answers: ["INSPEKTOR MESA", "POVJESNIČAR", "MEHANIČAR", "POŠTAR"]
  },
  {
    question: "TKO JE DIZAJNIRAO PRVI HELIKOPTER ZA MASOVNU PROIZVODNJU?",
    answers: ["IGOR SIKORSKY", "ELMER SPERRY", "GOTTLIEB DAIMLER", "FERDINAND VON ZEPPELIN"]
  },
  {
    question: "U DRUGOM SVJETSKOM RATU AMERIČKI VOJNICI KORISTILI SU PRVI KOMERCIJALNI SPREJ. KAKAV JE BIO TAJ SPREJ?",
    answers: ["INSEKTICID", "ANTISEPTIK", "TEKUĆINA ZA ČIŠĆENJE", "KREMA ZA BRIJANJE"]
  },
  {
    question: "KOJI AMERIČKI PREDSJEDNIK SE POJAVIO U SERIJI 'LAUGH-IN'?",
    answers: ["RICHARD NIXON", "LYNDON JOHNSON", "JIMMY CARTER", "RONALD REAGAN"]
  },
  {
  question: "KAKO SE ZOVE PRVI FILM BEATLESA?",
  answers: ["A HARD DAY'S NIGHT", "HELP!", "MAGICAL MYSTERY TOUR", "YELLOW SUBMARINE"]
},
{
  question: "KOJI PJEVAČ GLUMI JIMMYJA “B-RABBITA” SMITHA U FILMU “8 MILE”?",
  answers: ["EMINEM", "50 CENT", "SNOOP DOGG", "DR. DRE"]
},
{
  question: "ŠTO SU PO ZANIMANJU LIKOVI IZ FILMOVA “KUDUZ”, “MARŠAL” I “CRVENA PRAŠINA”?",
  answers: ["POLICAJCI", "NOVINARI", "VOZAČI", "PROFESORI"]
},
{
  question: "KOJI JE KLASIČNI PLES NAJZASTUPLJENIJI U BARU “PLAVA KAMENICA” IZ “POLICIJSKE AKADEMIJE”?",
  answers: ["TANGO", "VALCER", "SAMBA", "FOXTROT"]
},
{
  question: "KOJI NASLOV DIJELE PRVA EPIZODA “NAŠEG MALOG MISTA” I FILM MARTINA SCORSESEA IZ 2004.?",
  answers: ["AVIATOR", "CASINO", "TAXI DRIVER", "GOODFELLAS"]
},
{
  question: "GDJE SE, PO WIMU WENDERSU, NALAZI PARIZ?",
  answers: ["TEXAS", "NJEMAČKA", "ITALIJA", "ŠPANJOLSKA"]
},
{
  question: "TKO JE REŽIRAO FILM “LOVAC NA JELENE”?",
  answers: ["MICHAEL CIMINO", "FRANCIS FORD COPPOLA", "OLIVER STONE", "STANLEY KUBRICK"]
},
{
  question: "KOJA JE ŽIVOTINJA PRIKAZANA NA PLAKATU FILMA “KAD JAGANJCI UTIHNU”?",
  answers: ["LEPTIR", "PAUK", "PTICA", "ZMija"]
},
{
  question: "U KOJEM FILMU TIM ROBBINS BJEŽI IZ ZATVORA NAKON 19 GODINA KROZ TUNEL?",
  answers: ["THE SHAWSHANK REDEMPTION", "ESCAPE PLAN", "GREEN MILE", "PRISONERS"]
},
{
  question: "KAKO SE ZOVE OTOK IZ FILMA “RALJE” KOJI TERORIZIRA MORSKI PAS?",
  answers: ["AMITY ISLAND", "LIBERTY ISLAND", "PARADISE ISLAND", "OCEAN ISLAND"]
},
{
  question: "KAKO SE ZOVE OTOK U FILMU “SHUTTER ISLAND”?",
  answers: ["SHUTTER ISLAND", "BLACK ROCK", "DEVIL'S ISLAND", "ALCATRAZ"]
},
{
  question: "KAKO SE ZVALA MAJKA JAMESA BONDA PRIJE NEGO JE UPOZNALA ANDREWA BONDA?",
  answers: ["MONIQUE DELACROIX", "ANNA SMITH", "MARIE DUPONT", "ELLA BROWN"]
},
{
  question: "KOJI GLUMAC GLUMI NORDBERGA U FILMOVIMA “GOLO PIŠTOLJ”?",
  answers: ["O.J. SIMPSON", "EDDIE MURPHY", "SAMUEL L. JACKSON", "DENZEL WASHINGTON"]
},
{
  question: "KOJI NBA IGRAČ SE BORIO PROTIV BRUCE LEEJA U FILMU “ZMAJEVA IGRA SMRTI”?",
  answers: ["KAREEM ABDUL-JABBAR", "MICHAEL JORDAN", "MAGIC JOHNSON", "SHAQUILLE O'NEAL"]
},
{
  question: "KAKO SE ZOVU GLUMCI KOJI GLUME LOŠEG I ZLOG U FILMU “DOBAR, LOŠ, ZAO”?",
  answers: ["LEE VAN CLEEF I ELI WALLACH", "AL PACINO I ROBERT DE NIRO", "CLINT EASTWOOD I MORGAN FREEMAN", "JACK NICHOLSON I DUSTIN HOFFMAN"]
},
{
  question: "KOJI JE FILM IZ 2022. NASTAVAK DOGAĐAJA IZ “SPIDER-MAN: NO WAY HOME”?",
  answers: ["DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS", "SPIDER-MAN: FAR FROM HOME", "VENOM 2", "BLACK PANTHER: WAKANDA FOREVER"]
},
{
  question: "KOJU JE GLAZBENU ZVIJEZDU UTJELOVIO RAMI MALEK U FILMU IZ 2018.?",
  answers: ["FREDDIE MERCURY", "ELTON JOHN", "DAVID BOWIE", "PRINCE"]
},
{
  question: "U KAKVOM SE OBJEKTU ODVIJA VEĆI DIO RADNJE FILMA “ŽIVOT JE LIJEP”?",
  answers: ["KONCENTRACIJSKI LOGOR", "BOLNICA", "ŠKOLA", "ZATVOR"]
},
{
  question: "ŠTO JE ZLATNO NA FILMSKOM FESTIVALU U VENECIJI?",
  answers: ["LAV", "MEDVJED", "PALMA", "ARENA"]
},
{
  question: "KAKO SE ZOVE FILM IZ 1986. ZA KOJI JE PAUL NEWMAN DOBIO OSCARA?",
  answers: ["THE COLOR OF MONEY", "COOL HAND LUKE", "BUTCH CASSIDY", "THE VERDICT"]
},
{
  question: "KAKO SE ZOVE PRVI FILM ELVISA PRESLEYJA?",
  answers: ["LOVE ME TENDER", "JAILHOUSE ROCK", "BLUE HAWAII", "KING CREOLE"]
},
  {
    question: "KOJI BI VRH NEODOLJIVO PRIVUKAO HARRYJA POTTERA?",
    answers: ["KLEK", "JAPETIĆ", "SLJEME", "SVETA GERA"]
  },
  {
    question: "POLAZAK NARITA, ODREDIŠTE KEFLAVIK – ČIME PUTUJETE?",
    answers: ["AVIONOM", "RAKETOM", "ŽELJEZNICOM", "ŽIČAROM"]
  },
  {
    question: "KOJI JE IMOĆANIN ROĐEN U SPLITU PROSLAVIO PULU?",
    answers: ["MATE PARLOV", "MARIJAN BENEŠ", "ANTUN JOSIPOVIĆ", "ŽELJKO MAVROVIĆ"]
  },
  {
  question: "KAKO SE ZOVE AUTOR KOJI JE STVORIO PROFESORA BALTAZARA?",
  answers: ["ZLATKO GRGIĆ", "DUŠAN VUKOTIĆ", "VLADO KRISTL", "BORIVOJ DOVNIKOVIĆ"]
},
{
  question: "AKO SE NEŠTO ČUDNO DOGAĐA U VAŠEM SUSJEDSTVU, ONI SU PETER, EGON, RAYMOND I WINSTON. KOJE JE NJIHOVO ZANIMANJE?",
  answers: ["LOVCI NA DUHOVE", "POLICAJCI", "VATROGASCI", "ZNANSTVENICI"]
},
{
  question: "KAKO SE ZOVE PODMORNICA U FILMU IZ 1990. U KOJEM SU GLAVNI LIKOVI MARKO RAMIUS I JACK RYAN?",
  answers: ["RED OCTOBER", "NAUTILUS", "SEAWOLF", "POSEIDON"]
},
{
  question: "KAKO SE ZOVE VJERNI SOBAR INSPEKTORA JACQUESA CLOUSEAUA?",
  answers: ["CATO", "IGOR", "ALFRED", "JEEVES"]
},
{
  question: "U KOJEM JE FILMU NICOLAS CAGE 1995. OSVOJIO OSCARA GLUMEĆI SUICIDALNOG ALKOHOLIČARA?",
  answers: ["LEAVING LAS VEGAS", "CON AIR", "FACE/OFF", "THE ROCK"]
},
{
  question: "KAKO GLASI PUNO IME LIKA KOJEG U FILMU “LOVAC NA JELENE” (1978.) GLUMI CHRISTOPHER WALKEN?",
  answers: ["NIKANOR 'NICK' CHEVOTAREVICH", "MICHAEL VROON", "STEVEN PUSHKOV", "JOHN KOVAC"]
},
{
  question: "KOJEG DIKTATORA UTJELOVLJUJE FOREST WHITAKER U FILMU “POSLJEDNJI KRALJ ŠKOTSKE”?",
  answers: ["IDI AMIN", "MUAMMAR GADDAFI", "ROBERT MUGABE", "JOSEPH KABILA"]
},
{
  question: "KAKO SE PREZIVAJU NAJPOZNATIJI POGREBNICI I AUTOPRIJEVOZNICI U JUGOSLAVENSKOJ KINEMATOGRAFIJI?",
  answers: ["TOPALOVIĆ", "ČVOROVIĆ", "POPOVIĆ", "KOVAČEVIĆ"]
},
{
  question: "U KOJEM SE AFRIČKOM GRADU ODVIJA RADNJA FILMA “PAD CRNOG JASTREBA”?",
  answers: ["MOGADIŠU", "NAIROBI", "KIGALI", "LAGOS"]
},
{
  question: "KOJA DVA GLUMCA UTJELOVLJUJU BATMANA I SUPERMANA U FILMU “BATMAN V SUPERMAN”?",
  answers: ["BEN AFFLECK I HENRY CAVILL", "CHRISTIAN BALE I BRANDON ROUTH", "ROBERT PATTINSON I TOM WELLING", "MICHAEL KEATON I CHRISTOPHER REEVE"]
},
{
  question: "KOJE IME IDE ISPRED DB5 DA BI SE DOBILO IME NAJPOZNATIJEG BONDOVOG AUTOMOBILA?",
  answers: ["ASTON MARTIN", "ROLLS ROYCE", "JAGUAR", "BENTLEY"]
},
{
  question: "U KOJEM FILMU IZ 1989. MEG RYAN GLUMI ORGAZAM U RESTORANU?",
  answers: ["WHEN HARRY MET SALLY", "SLEEPLESS IN SEATTLE", "PRETTY WOMAN", "NOTTING HILL"]
},
{
  question: "POD KOJIM SE PSEUDONIMOM SKRIVA GLUMICA KIM COPPOLA?",
  answers: ["NICOLAS CAGE", "JOHN TRAVOLTA", "TOM CRUISE", "BRAD PITT"]
},
{
  question: "KOJA DVA GLUMCA GLUME TANGA I CASHA U FILMU “TANGO I CASH” (1989.)?",
  answers: ["SYLVESTER STALLONE I KURT RUSSELL", "ARNOLD SCHWARZENEGGER I BRUCE WILLIS", "MEL GIBSON I DANNY GLOVER", "JEAN-CLAUDE VAN DAMME I STEVEN SEAGAL"]
},
  {
    question: "ASKJA, HEKLA I KATLA IMENA SU ISLANDSKIH...",
    answers: ["VULKANA", "BOŽICA", "GRADOVA", "ZRAČNIH LUKA"]
  },
  {
  question: "KOJI DIO TIJELA JE GENE SIMMONS OSIGURAO NA MILIJUN DOLARA?",
  answers: ["JEZIK", "RUKE", "GLAS", "OČI"]
},
{
  question: "KOJA EUROPSKA DRŽAVA IMA HIMNU SA ČAK 158 STIHOVA?",
  answers: ["GRČKA", "ITALIJA", "FRANCUSKA", "ŠPANJOLSKA"]
},
{
  question: "KAKO SE ZOVE COMEDY ROCK SASTAV KOJI VODE JACK BLACK I KYLE GASS?",
  answers: ["TENACIOUS D", "THE LONELY ISLAND", "FLIGHT OF THE CONCHORDS", "STEEL PANTHER"]
},
{
  question: "ZA KOJI SU INSTRUMENT BILI ZADUŽENI JOHN BONHAM I KEITH MOON?",
  answers: ["BUBNJEVI", "GITARA", "BAS GITARA", "KLAVIJATURE"]
},
{
  question: "KOJI JE GITARIST DOBIO NADIMAK “KRALJ BLUESA”?",
  answers: ["B.B. KING", "ERIC CLAPTON", "MUDDY WATERS", "JIMI HENDRIX"]
},
{
  question: "KOJE SE DVIJE RIJEKE, UZ SAVU, SPOMINJU U HRVATSKOJ HIMNI?",
  answers: ["DRAVA I DUNAV", "KUPA I NERETVA", "MURA I CETINA", "UNA I ZRMANJA"]
},
{
  question: "U KOJEM JE GRADU ROĐEN WOLFGANG AMADEUS MOZART?",
  answers: ["SALZBURG", "BEČ", "GRAZ", "LINZ"]
},
{
  question: "KAKO SE ZVAO FRONTMEN BENDA CRVENI KORALJI?",
  answers: ["BORIS BIZETIĆ", "ĐORĐE MARJANOVIĆ", "ZDENKO RUNJIĆ", "DRAGO MLINAREC"]
},
{
  question: "KOJE DVIJE HRVATSKE PJEVAČICE IZVODE PJESMU “JA SAM VLAK”?",
  answers: ["ENI JURIŠIĆ I VESNA PISAROVIĆ", "SEVERINA I DANIJELA MARTINOVIĆ", "MAJA BLAGDAN I NINA BADRIĆ", "JELENA ROZGA I LANA JURČEVIĆ"]
},
{
  question: "KAKO SE ZVALA SPLITSKA GRUPA U KOJOJ JE PJEVALA MAJA BLAGDAN?",
  answers: ["STIJENE", "DALMATINO", "MAGAZIN", "TUTTI FRUTTI"]
},
{
  question: "KAKO SE ZOVE JAMES BOND FILM S PJESMOM “YOU KNOW MY NAME” CHRISA CORNELLA?",
  answers: ["CASINO ROYALE", "SKYFALL", "GOLDENEYE", "SPECTRE"]
},
{
  question: "NA KOJEM JE INSTRUMENTU BIO VIRTUOZ FRANZ LISZT?",
  answers: ["KLAVIR", "VIOLINA", "ORGULJE", "HARFA"]
},
{
  question: "KAKO SE ZOVE PRVI PJEVAČ THE SMITHSA?",
  answers: ["MORRISSEY", "JOHNNY MARR", "ANDY ROURKE", "MIKE JOYCE"]
},
{
  question: "KAKO SE ZOVE TURNeJA BIJELOG DUGMETA POKRENUTA 2024. GODINE?",
  answers: ["DOŽIVJETI STOTU", "LIPE CVATU", "BITANGA I PRINCEZA", "NAPILE SE ULICE"]
},
{
  question: "KOJE SE DVIJE RIJEKE SPOMINJU U PJESMI “LJUBAV SE NE TRŽI”?",
  answers: ["SAVA I DRAVA", "DUNAV I DRINA", "NERETVA I CETINA", "KUPA I MURA"]
},
{
  question: "KOJE SU ŽENSKO IME OPJEVALI PRO ARTE, ZDRAVKO ČOLIĆ I SENAD OD BOSNE?",
  answers: ["SUZANA", "JELENA", "MARIJA", "ANITA"]
},
{
  question: "KOJA JE HRVATSKA PJEVAČICA POČELA KAO KLAVIJATURISTICA U BENDU TOMISLAVA IVČIĆA?",
  answers: ["MERI CETINIĆ", "NINA BADRIĆ", "SEVERINA", "JOSIPA LISAC"]
},
{
  question: "KOJA VERDIJEVA OPERA DIJELI IME S PJESMOM HLADNOG PIVA?",
  answers: ["AIDA", "TRAVIATA", "RIGOLETTO", "OTELLO"]
},
  {
    question: "KOJI OD KEMIJSKIH ELEMENATA NIJE NAZVAN PO NOBELOVCU?",
    answers: ["AJNŠTAJNIJ", "FERMIJ", "KIRIJ", "NOBELIJ"]
  },
  {
    question: "HENRY MILLER JE ZA OPSCENOST NAPADAN ZBOG SVOJIH:",
    answers: ["OBRATNICA", "POLARNICA", "EKVATORA", "MERIDIJANA"]
  },
  {
    question: "KOJE JE KAZALIŠTE NAJSTARIJE U HRVATSKOJ?",
    answers: ["HVARSKO", "RIJEČKO", "SPLITSKO", "DUBROVAČKO"]
  },
  {
    question: "KAKO SE ZOVE ALBUM DINE DVORNIKA IZ 1993. GODINE?",
    answers: ["PRIRODA I DRUŠTVO", "MATEMATIKA", "ZEMLJOPIS", "TJELESNI ODGOJ"]
  },
  {
    question: "JELEN VRLO RAZGRANATIH ROGOVA U LOVAČKOM ŽARGONU ZOVE SE:",
    answers: ["KAPITALAC", "KAPITALIST", "BURŽUJ", "ARISTOKRAT"]
  },
  {
    question: "KAKO GLASI NARODNI NAZIV ZA VENERU?",
    answers: ["DANICA", "MARICA", "KATICA", "SLAVICA"]
  },
  {
    question: "'LABUĐE JEZERO' P. ILIČA ČAJKOVSKOG JE...",
    answers: ["BALET", "SIMFONIJA", "MJUZIKL", "OPERETA"]
  },
  {
    question: "KOJE ZANIMANJE POVEZUJEMO S IMENOM VARAŽDINCA LJUBOMIRA KEREKEŠA?",
    answers: ["GLUMAC", "NOGOMETAŠ", "POLITIČAR", "ARHITEKT"]
  },
  {
    question: "TKO JE NAKON POSUDBE DUGE 442 GODINE, 20. PROSINCA 1999., MAKAO VRATIO KINI?",
    answers: ["PORTUGALCI", "ENGLEZI", "NIZOZEMCI", "FRANCUZI"]
  },
  {
    question: "ŠTO JE KOD CZESŁAWA MIŁOSZA ZAROBLJENO, A KOD IMMANUELA KANTA ČISTO I PRAKTIČNO?",
    answers: ["UM", "SILA", "ENERGIJA", "ZNANJE"]
  },
  {
    question: "KOJI SISAVAC NESE JAJA?",
    answers: ["ČUDNOVATI KLJUNAŠ", "KOALA", "PLAVETNI KIT", "DUPIN"]
  },
  {
    question: "SAMURAJSKI KODEKS ZOVE SE...",
    answers: ["BUSHIDO", "HARAKIRI", "KENDO", "AIKIDO"]
  },
  {
  question: "U KOJEM JE GRADU UMR0 JIMI HENDRIX 1970. GODINE?",
  answers: ["LONDON", "NEW YORK", "LOS ANGELES", "SEATTLE"]
},
{
  question: "KAKO SE ZOVE GLAZBENI ČASOPIS NADAHNUT PJESMOM BOBA DYLANa?",
  answers: ["ROLLING STONE", "SPIN", "NME", "BILLBOARD"]
},
{
  question: "KOJI JE NJUJORŠKI BEND IMAO HITOVE “DENISE”, “HANGING ON THE TELEPHONE” I “HEART OF GLASS”?",
  answers: ["BLONDIE", "RAMONES", "TALKING HEADS", "THE STROKES"]
},
{
  question: "ČIJA JE 41. SIMFONIJA POZNATA KAO “JUPITEROVA SIMFONIJA”?",
  answers: ["MOZARTOVA", "BEETHOVENOVA", "HAYDNOVA", "SCHUBERTOVA"]
},
{
  question: "KAKO SE ZOVE PRVI ALBUM GRUPE U2 IZ 1980. GODINE?",
  answers: ["BOY", "WAR", "OCTOBER", "THE JOSHUA TREE"]
},
{
  question: "IZ KOJE POKRAJINE POTJEČE PJESMA “MOJA DIRIDIKA”?",
  answers: ["DALMACIJA", "SLAVONIJA", "ISTRA", "MEĐIMURJE"]
},
{
  question: "KOJE JE GODINE UMRO MICHAEL JACKSON?",
  answers: ["2009", "2012", "2005", "2015"]
},
{
  question: "POD KOJIM JE PSEUDONIMOM POZNAT EDIN OSMIĆ?",
  answers: ["EDO MAAJKA", "FRENKIE", "GENERAL WOO", "TARGET"]
},
{
  question: "POD KOJIM JE UMJETNIČKIM IMENOM POZNATA EILLEEN EDWARDS?",
  answers: ["SHANIA TWAIN", "CELINE DION", "ALANIS MORISSETTE", "DIDO"]
},
{
  question: "KAKO GLASI PUNO IME EMINEMA?",
  answers: ["MARSHALL BRUCE MATHERS III", "MICHAEL MARSHALL MATHERS", "MARK MATHERS", "MATTHEW MARSHALL"]
},
{
  question: "KOJI SE PROJEKTIL SPOMINJE U HIT PJESMI BRUNE MARSA IZ 2010.?",
  answers: ["GRENADE", "MISSILE", "ROCKET", "BOMB"]
},
{
  question: "KOJI DAN U TJEDNU MRZE GARFIELD I BORIS NOVKOVIĆ?",
  answers: ["PONEDJELJAK", "UTORAK", "SRIJEDA", "PETAK"]
},
{
  question: "KOJI NADIMAK DIJELE EISENHOWER I SUPRUG TINE TURNER?",
  answers: ["IKE", "DUKE", "KING", "DOC"]
},
  {
    question: "GLAGOLSKI OBLICI KOJIMA U HRVATSKOM OZNAČAVAMO PROŠLOST SU PERFEKT, PLUSKVAMPERFEKT, AORIST I...",
    answers: ["IMPERFEKT", "INFINITIV", "IMPERATIV", "INDIKATIV"]
  },
  {
    question: "KOJA LJEPOTICA NAJBOLJE PRISTAJE UZ NOGOMETAŠA ROBERTA KOVAČA?",
    answers: ["ANICA MARTINOVIĆ", "IVA RADIĆ", "FANI ĆAPALIJA", "JELENA MEDIĆ"]
  },
  {
    question: "BACIL JE BAKTERIJA U OBLIKU:",
    answers: ["ŠTAPIĆA", "KUGLICE", "GROZDA", "SPIRALE"]
  },
  {
    question: "KOJI SE OD NAVEDENIH NAZIVA NE ODNOSI NA NAJVIŠI VRH NA ZEMLJI?",
    answers: ["MOLOKAI", "CHOMOLUNGMA", "MOUNT EVEREST", "SAGARMATHA"]
  },
  {
    question: "KAKO SE SLIKOVITO ZOVE ZRAKOPLOV?",
    answers: ["ČELIČNA PTICA", "ZLATNA PTICA", "BAKRENA PTICA", "OLOVNA PTICA"]
  },
  {
    question: "HVATAČ HVATA, BACAČ BACA, UDARAČ UDARA. KOJI JE TO SPORT?",
    answers: ["BEJZBOL", "ODBOJKA", "HOKEJ", "NOGOMET"]
  },
  {
    question: "KOJOJ VRSTI RIJEČI PRIPADA RIJEČ KUTOMJER?",
    answers: ["IMENICA", "GLAGOL", "PRIDJEV", "PRIJEDLOG"]
  },
  {
    question: "KAKO SE ZOVE ŽABAC KOJI PREDVODI MUPPETE?",
    answers: ["KERMIT", "RALF", "GONZO", "WALDORF"]
  },
  {
    question: "'ZDENAC ŽIVOTA' IVANA MEŠTROVIĆA NALAZI SE U ZAGREBU ISPRED:",
    answers: ["KAZALIŠTA", "BURZE", "VIJEĆNICE", "SABORA"]
  },
  {
    question: "LATIĆE CVIJETA ČINE VJENČIĆ, A LAPOVI CVIJETA:",
    answers: ["ČAŠKU", "ČOKOT", "LISKU", "GROZD"]
  },
  {
    question: "TKO SE NATJEČE U KLASI 'OPTIMIST'?",
    answers: ["JEDRILIČARI", "SANJKAŠI", "MOTOCIKLISTI", "BICIKLISTI"]
  },
  {
    question: "RENESANSNI LJETNIKOVAC TVRDALJ NALAZI SE U STAROM GRADU:",
    answers: ["STAROM GRADU", "STARIGRADU", "NOVIGRADU", "BIOGRADU"]
  },
  {
    question: "KOLIKO BAJTOVA IMA 1 KILOBAJT?",
    answers: ["1024", "1000", "1104", "1011"]
  },
  {
    question: "KOJA OD NAVEDENIH ŽIVOTINJA NE SPADA U SKUPINU MORSKIH PASA?",
    answers: ["ORKA", "BIJELA PSINA", "MLAT", "MODRULJ"]
  },
  {
    question: "NA SVOJE PRVO PUTOVANJE KOLUMBO KREĆE:",
    answers: ["1492.", "1496.", "1497.", "1500."]
  },
  {
    question: "ČEŠKI SU EVANGELICI 1618. 'UPRILIČILI' DEFENESTRACIJU, ODNOSNO BACANJE KRALJEVSKOGA NAMJESNIKA:",
    answers: ["KROZ PROZOR", "POD VLAK", "U ŽIVO BLATO", "S MOSTA"]
  },
  {
    question: "KAKO SE JOŠ NA HRVATSKOM KAŽE 'SLIJEPO CRIJEVO'?",
    answers: ["CRVULJAK", "SLJEPIĆ", "VISULJAK", "CRIJEVULJAK"]
  },
  {
    question: "U KOJOJ DRŽAVI ŽIVE KRAŠOVANI?",
    answers: ["U RUMUNJSKOJ", "U MAĐARSKOJ", "U POLJSKOJ", "U UKRAJINI"]
  },
  {
    question: "ŠTO JE PO NARODNOSTI MIKA HAKKINEN?",
    answers: ["FINAC", "ŠKOT", "POLJAK", "DANAC"]
  },
  {
    question: "KOLIKO GODINA TRAJE MANDAT PREDSJEDNIKA HRVATSKE?",
    answers: ["5", "3", "4", "6"]
  },
  {
    question: "GUDAČKI TRIO ČINE VIOLINA, VIOLA I...",
    answers: ["VIOLONČELO", "MANDOLINA", "KONTRABAS", "HARFA"]
  },
  {
    question: "POD KOJIM JE NAZIVOM JAVNOSTI POZNATIJI PLIVIN ANTIBIOTIK AZITHROMYCIN?",
    answers: ["SUMAMED", "ANDOL", "ASPIRIN", "PLIVADON"]
  },
  {
    question: "KOJA JE VELIKAŠKA OBITELJ ČETIRI STOLJEĆA GOSPODARILA TRAKOŠĆANOM?",
    answers: ["DRAŠKOVIĆ", "FRANKOPAN", "ŠUBIĆ", "ERDÖDY"]
  },
  {
    question: "ŠTO JE PO NARODNOSTI ISTRAŽIVAČ FERDINAND MAGELLAN?",
    answers: ["PORTUGALAC", "ŠPANJOLAC", "FRANCUZ", "TALIJAN"]
  },
  {
    question: "UOBIČAJENI NAZIV ZA CESTU OD KARLOVCA DO SENJA JE:",
    answers: ["JOZEFINA", "KAROLINA", "LUJZIJANA", "PAULINA"]
  },
  {
    question: "NEKAD JUŽNA RODEZIJA, A DANAS?",
    answers: ["ZIMBABVE", "KONGO", "UGANDA", "MOZAMBIK"]
  },
  {
    question: "KAKO SE ZOVE GROTESKNI LIK TURSKOG KAZALIŠTA SJENKI I JUNAK ANDRIĆEVE 'PROKLETE AVLIJE'?",
    answers: ["KARAĐOZ", "SIMAN", "DŽEM-SULTAN", "ĐERZELEZ"]
  },
  {
    question: "KOJI JE OD NAVEDENIH NAZIV PUSTINJE, A NE DRŽAVE?",
    answers: ["NAMIB", "GABON", "NIGER", "MALI"]
  },
  {
    question: "TOMAŠ MASARYK BIO JE PREDSJEDNIK:",
    answers: ["ČEHOSLOVAČKE", "POLJSKE", "BUGARSKE", "MAĐARSKE"]
  },
  {
    question: "KAKO JE IME APOLONOVOJ SVEĆENICI IZ DELFA?",
    answers: ["PITIJA", "KIRKA", "IFIGENIJA", "KASANDRA"]
  },
  {
    question: "KOJI JE DRŽIĆEV LIK ZNAN PO ŠKRTOSTI SAKRIVAO TEZORO U ĆUPU?",
    answers: ["SKUP", "POMET", "STANAC", "BOKČILO"]
  },
  {
    question: "KOJI JE NAŠ NAZIV ZA EKVATOR?",
    answers: ["RAVNODNEVNIK", "POLUTNIK", "KOLUTNIK", "PRISOJNIK"]
  },
  {
    question: "IZ KOJE AFRIČKE DRŽAVE DOLAZI KOFI ANNAN, GLAVNI TAJNIK UN-A?",
    answers: ["GANE", "KAMERUNA", "TUNISA", "NIGERIJE"]
  },
  {
    question: "TV SPORTSKA NOVINARKA, OSTVARILA JE USPJEŠNU KARIJERU U:",
    answers: ["ATLETICI", "GIMNASTICI", "UMJETNIČKOM KLIZANJU", "RUKOMETU"]
  },
  {
    question: "FRANCUSKA JE HIMNA POSTALA POPULARNA ZAHVALJUJUĆI DRAGOVOLJCIMA IZ:",
    answers: ["MARSEILLA", "PARIZA", "BORDEAUXA", "STRASBOURA"]
  },
  {
    question: "KAKO NAZIVAMO OŠTAR ZVUK KOJI PROIZVODI JAK VJETAR?",
    answers: ["FIJUK", "CIJUK", "JAUK", "PIJUK"]
  },
  {
    question: "KOGA JE U NASLOVU SVOGA ROMANA MEŠA SELIMOVIĆ SUOČIO SA SMRĆU?",
    answers: ["DERVIŠA", "IMAMA", "MUJEZIMA", "HODŽU"]
  },
  {
    question: "S KOJOM SU PJESMOM 'NOVI FOSILI' NA EUROVIZIJI 1987. OSVOJILI 4. MJESTO?",
    answers: ["JA SAM ZA PLES", "ŽELJO MOJA", "MANGUP", "ROCK ME BABY"]
  },
  {
    question: "AKO JE NAKON 'PSIHA' TRAUMATIČNO POSTALO TUŠIRANJE, NAKON 'MARATONCA' TRAUMATIČAN JE POSTAO ODLAZAK:",
    answers: ["ZUBARU", "MESARU", "FRIZERU", "BANKARU"]
  },
  {
    question: "DOK JE IZRAELCI NISU OKUPIRALI 1967., GOLANSKA VISORAVAN JE BILA U SASTAVU:",
    answers: ["SIRIJE", "EGIPTA", "LIBANONA", "JORDANA"]
  },
  {
    question: "KOJI SE KUKAC LATINSKOG NAZIVA DROSOPHILA MELANOGASTER ČESTO UPOTREBLJAVA U GENETIČKIM POKUSIMA?",
    answers: ["VINSKA MUŠICA", "BOGOMOLJKA", "KRUMPIROVA ZLATICA", "PČELA"]
  },
  {
    question: "KAKO SE ZOVE GLAVNI GRAD UZBEKISTANA?",
    answers: ["TAŠKENT", "BAKU", "SAMARKAND", "MAHAČKALA"]
  },
  {
    question: "NAZIV 'OPEKARNA' ODNOSI SE NA:",
    answers: ["CIGLANU", "PILANU", "DVORANU", "TOPLANU"]
  },
  {
    question: "'IMA JEDNA MODRA RIJEKA, VALJA NAMA...', U PJESMI MAKA DIZDARA.",
    answers: ["PITI", "MLIJEKA", "DO OSJEKA", "PREKO RIJEKE"]
  },
  {
    question: "U FILMSKOM JE SVIJETU KAO 'BB' ZNANA JEDNA I JEDINA...",
    answers: ["BRIGITTE", "BARBARA", "BEATRICE", "BERNADETTE"]
  },
  {
    question: "KAKO U TENISU NAZIVAMO PRIJESTUP PRI IZVOĐENJU SERVISA?",
    answers: ["FOOT FAULT", "BREAK POINT", "POLE POSITION", "TIE BREAK"]
  },
  {
    question: "VUKOTIĆ JE U 'SUROGATU' DUHOVITO PRIKAZAO SUVREMENU CIVILIZACIJU PREPLAVLJENU:",
    answers: ["UMJETNIM TVOREVINAMA", "RATOVIMA", "KISELIM KIŠAMA", "NUKLEARNIM OTPADOM"]
  },
  {
    question: "U ČEMU JE SVJETSKI UGLED STEKAO KORADO KORLEVIĆ?",
    answers: ["ASTRONOMIJI", "BOTANICI", "MEDICINI", "PSIHOLOGIJI"]
  },
  {
    question: "ŠTO SAČINJAVA DOBRE 3/4 ČISTOGA ZRAKA?",
    answers: ["DUŠIK", "KISIK", "UGLJIK", "VODIK"]
  },
  {
    question: "KOJI JE HRVATSKI SPORTAŠ NASTUPIO I NA LJETNIM I NA ZIMSKIM OLIMPIJSKIM IGRAMA?",
    answers: ["IGOR BORASKA", "KREŠIMIR ČULJAK", "IVAN ŠOLA", "VEDRAN PAVLEK"]
  },
  {
    question: "KOJI JE GRAD DO 1966., PRIJE BRUXELLESA, BIO GLAVNO SJEDIŠTE NATO-a?",
    answers: ["PARIZ", "WASHINGTON", "BONN", "MADRID"]
  },
  {
    question: "KOJI JE PIROMAN, ŽELJAN VJEČNE SLAVE, ZAPALIO ARTEMIDIN HRAM U EFEZU?",
    answers: ["HEROSTRAT", "POLIMIK", "NERON", "ETEOKLO"]
  },
  {
    question: "'OLD FAITHFUL' IME JE NAJPOZNATIJEG SVJETSKOG:",
    answers: ["GEJZIRA", "NACIONALNOG PARKA", "VULKANA", "VODOPADA"]
  },
  {
    question: "GLAVNI GRAD BENINA JE:",
    answers: ["PORTO NOVO", "PORTO STARO", "PORTO VISOKO", "PORTO NISKO"]
  },
  {
    question: "KAKO NAZIVAMO GRANICU DVIJU DRŽAVA KOJA SE PROLAZI BEZ VEĆIH FORMALNOSTI?",
    answers: ["MEKA", "SPOREDNA", "PRISTUPAČNA", "TOPLA"]
  },
  {
    question: "KAKO SE ZOVE PRVI STUPANJ U KOMPARACIJI PRIDJEVA?",
    answers: ["POZITIV", "NEGATIV", "ABLATIV", "KOMPARATIV"]
  },
  {
    question: "KAKO JE PREZIME GRGI, CRTANOM LIKU ISMETA VOLJEVICE?",
    answers: ["ČVARAK", "PROTOKOL", "ČOKOLIN", "GRMALJ"]
  },
  {
    question: "NASEOBINU EPIDAUR GRCI SU OSNOVALI NA MJESTU DANAŠNJEG:",
    answers: ["CAVTATA", "VRSARA", "ZADRA", "OMIŠA"]
  },
  {
    question: "KOJI NAROD NE GOVORI GERMANSKIM JEZIKOM?",
    answers: ["FINCI", "DANCI", "ŠVEĐANI", "ISLANĐANI"]
  },
  {
    question: "SVOJEVRSTAN UVOD ZA AMERIČKI GRAĐANSKI RAT BILA JE TZV. BOSTONSKA:",
    answers: ["ČAJANKA", "USPAVANKA", "PIJANKA", "KAJDANKA"]
  },
  {
    question: "NAKON FELINIJEVA FILMA 'SLATKI ŽIVOT' SVIJET JE POSTAO BOGATIJI ZA JEDAN TERMIN:",
    answers: ["PAPARAZZO", "CAPPUCCINO", "CHIAROSCURO", "CALCIO"]
  },
  {
    question: "KOJI SVETAC JE ZAŠTITNIK ENGLESKE?",
    answers: ["SVETI JURAJ", "SVETI JAKOV", "SVETI IVAN", "SVETI ANTON"]
  },
  {
    question: "KOJI JE FRANCUSKI KNJIŽEVNIK AUTOR ROMANA 'ZVONAR CRKVE NOTRE-DAME'?",
    answers: ["VICTOR HUGO", "HONORE DE BALZAC", "GUSTAVE FLAUBERT", "EMILE ZOLA"]
  },
  {
    question: "KAKO JE U NAS PREVEDEN 'DIRTY HARRY', PRVI FILM IZ SERIJALA O PRLJAVOM HARRYJU?",
    answers: ["ŠKORPION UBIJA", "U VRELINI NOĆI", "TEŠKA META", "NA NIŠANU SNAJPERA"]
  },
  {
    question: "KAKO SE NAZIVA SMRTONOSNO ORUŽJE, KIŠOBRAN SA ZAŠILJENIM VRHOM UMOČENIM U OTROV?",
    answers: ["BUGARSKI KIŠOBRAN", "ALBANSKI KIŠOBRAN", "RUMUNJSKI KIŠOBRAN", "NJEMAČKI KIŠOBRAN"]
  },
  {
    question: "KOJE SE BJELGORIČNO DRVO UVUKLO MEĐU CRNOGORIČNO DRVEĆE?",
    answers: ["KESTEN", "SMREKA", "JELA", "TISA"]
  },
  {
    question: "KOJI JE ZNANSTVENIK OTKRIO BACIL TUBERKULOZE?",
    answers: ["ROBERT KOCH", "WILHELM ROENTGEN", "CESARE LOMBROSO", "LOUIS PASTEUR"]
  },
  {
    question: "KAKO SE ZOVE DVOSLOŽNA PJESNIČKA STOPA?",
    answers: ["JAMB", "LIMB", "DITIRAMB", "ROMB"]
  },
  {
    question: "BRDO NA KOJEM SU PRONAĐENI OSTACI KRAPINSKOG PRAČOVJEKA ZOVE SE...",
    answers: ["HUŠNJAKOVO BRDO", "ČEŠNJAKOVO BRDO", "BOŠNJAKOVO BRDO", "LJEŠNJAKOVO BRDO"]
  },
  {
    question: "KAKO SE ZOVE VLASNICA HALJINE O KOJOJ SE 1998. BRUJILO U CIJELOM WASHINGTONU?",
    answers: ["MONICA LEWINSKY", "VENUS WILLIAMS", "MADONNA", "JENNIFER LOPEZ"]
  },
  {
    question: "KAKO SE ZOVE NAJGUŠĆI DIO ATMOSFERE U KOJEM SE ZBIVAJU METEOROLOŠKE PROMJENE?",
    answers: ["TROPOSFERA", "EGZOSFERA", "NANOSFERA", "TERMOSFERA"]
  },
  {
    question: "KOJA JE ŽLIJEZDA ČOVJEČJEG ORGANIZMA NAJVEĆA?",
    answers: ["JETRA", "ŠTITNJAČA", "GUŠTERAČA", "HIPOFIZA"]
  },
  {
    question: "KOJI JE RIMLJANIN PRVI POČEO MJERITI PULS U DIJAGNOSTIČKE SVRHE?",
    answers: ["GALEN", "JUVENAL", "PLAUT", "PLUTARH"]
  },
  {
    question: "ŠTO U DOSLOVNOM PRIJEVODU ZNAČI GALICIZAM ŠOFER?",
    answers: ["LOŽAČ", "PUTNIK", "CESTA", "VOZAČ"]
  },
  {
    question: "NAJPOZNATIJA SLIKA EDVARDA MUNCHA JEST:",
    answers: ["KRIK", "GRČ", "SAN", "UZDAH"]
  },
  {
    question: "NA KOLIKO KOTAČA POBJEĐUJE LANCE ARMSTRONG?",
    answers: ["2", "8", "4", "3"]
  },
  {
    question: "RENEOVA SUPRUGA U SERIJI 'ALO, ALO' ZOVE SE:",
    answers: ["EDITTE", "HELGA", "MICHELLE", "YVETTE"]
  },
  {
    question: "KOJE JE MJESTO RODNO MJESTO TINA UJEVIĆA?",
    answers: ["VRGORAC", "RASTUŠJE", "DRINOVCI", "LUKOVDOL"]
  },
  {
    question: "KOJI OD NAVEDENIH PLESOVA NE POTJEČE S KUBE?",
    answers: ["SAMBA", "MAMBO", "RUMBA", "SALSA"]
  },
  {
    question: "TKO SE SUKOBIO U STOGODIŠNJEM RATU?",
    answers: ["FRANCUSKA I ENGLESKA", "ŠPANJOLSKA I FRANCUSKA", "ENGLESKA I NJEMAČKA", "NJEMAČKA I RUSIJA"]
  },
  {
    question: "BOŽICA AFRODITA RODILA SE IZ...",
    answers: ["MORSKE PJENE", "VATRE", "KORALJA", "RUŽE"]
  },
  {
    question: "KOLIKO NOGU IMA MRAV?",
    answers: ["6", "4", "10", "8"]
  },
  {
    question: "KOJA JE DAMA POSTALA PRVA MINISTRICA U HRVATSKOJ VLADI?",
    answers: ["LJILJA VOKIĆ", "LJERKA MINTAS-HODAK", "VESNA GIRARDI-JURKIĆ", "NANSI IVANIŠEVIĆ"]
  },
  {
    question: "KOJI REFLEKS LIJEČNIK PROVJERAVA UDARCEM U KOLJENO?",
    answers: ["PATELARNI", "LUMBALNI", "ABDOMINALNI", "DENTALNI"]
  },
  {
    question: "NAJSJEVERNIJA TOČKA EUROPE NALAZI SE U FINNMARKU:",
    answers: ["U NORVEŠKOJ", "U ŠVEDSKOJ", "U FINSKOJ", "U DANSKOJ"]
  },
  {
    question: "KAKO SE ZOVE NAJVEĆI OD 7000 FILIPINSKIH OTOKA?",
    answers: ["LUZON", "MINDANAO", "PALAWAN", "CEBU"]
  },
  {
    question: "KAKO SE ZOVE NASTAMBA SJEVERNOAMERIČKIH INDIJANACA?",
    answers: ["TIPI", "IGLU", "JURTA", "KOLIBA"]
  },
  {
    question: "KAKO SE ZOVE NOVČIĆ KOJIM SU GRCI PLAĆALI PRIJEVOZ PREKO STIKSA U HAD?",
    answers: ["OBOL", "DENAR", "TALENT", "DRAHMA"]
  },
  {
    question: "KAKO SE ZOVE OBIČAJNO PRAVO U ISLAMSKIH NARODA?",
    answers: ["ADAT", "ŠERIJAT", "SUNNA", "FETVA"]
  },
  {
    question: "KAKO SE ZOVE LIK KOJEG JE U 'DINASTIJI' GLUMILA LINDA EVANS?",
    answers: ["KRYSTLE CARRINGTON", "ALEXIS COLBY", "FALLON CARRINGTON", "DOMINIQUE DEVERAUX"]
  },
  {
    question: "KAKO SE ZOVE MAJKA BENJAMINA, 12. SINA JAKOVLJEVA, KOJA JE UMRLA PRI PORODU?",
    answers: ["RAHELA", "LEA", "SARA", "REBEKA"]
  },
  {
    question: "KAKO SE ZOVE MITOLOŠKO ČUDOVIŠTE U KOJEM SU SJEDINJENI LAV I ORAO?",
    answers: ["GRIFON", "KENTAUR", "MINOTAUR", "SFINGA"]
  },
  {
    question: "KOLIKO JE KAVALIRA IMALA KRLEŽINA GOSPOĐICA MELANIJA?",
    answers: ["TRI", "DVA", "PET", "JEDAN"]
  },
  {
    question: "KOLIKO JE MAĆEHA IMALA BLOODY MARY, ENGLESKA KRALJICA MARIJA TUDOR?",
    answers: ["DVIJE", "TRI", "JEDNU", "ČETIRI"]
  },
  {
    question: "KOME LIJEČNICI POLAŽU ZAKLETVU DA ĆE SAVJESNO I DOSTOJNO OBAVLJATI SVOJU DUŽNOST?",
    answers: ["HIPOKRATU", "GALENU", "ASKLEPIJU", "PLATONU"]
  },
  {
    question: "KOME SE DOGODILO UKAZANJE U LOURDESU?",
    answers: ["BERNADETTI SOUBIROUS", "IVANI ORLEANKI", "KATARINI SIENSKOJ", "TEREZI AVILSKOJ"]
  },
  {
    question: "KORDELIJA, REGAN I GOMERIL KĆERI SU KOJEG KRALJA?",
    answers: ["LEARA", "HAMLETA", "RICHARDA III", "MACBETHA"]
  },
  {
    question: "KAKO SE ZOVE KRAĆA SKLADBA NESTALNA OBLIKA, NAJČEŠĆE ZA KLAVIR?",
    answers: ["IMPROMPTU", "SONATA", "ETIDA", "SIMFONIJA"]
  },
  {
    question: "KOJU SU FRANCUSKU KRALJICU ZVALI 'UDOVICA CAPET'?",
    answers: ["MARIJA ANTOANETA", "MARIJA MEDICI", "KATARINA MEDICI", "ELEONORA AKVITANSKA"]
  },
  {
    question: "KOJA ŽIVOTINJA JE NAJČEŠĆE PRIKAZIVANA U MINOJSKOJ UMJETNOSTI NA KRETI?",
    answers: ["BIK", "KONJ", "LAV", "KOZA"]
  },
  {
    question: "KOLIKI JE ZBROJ SVIH KUTOVA U TROKUTU?",
    answers: ["180°", "360°", "90°", "270°"]
  },
  {
    question: "KOLIKO GODINA MORA NAVRŠITI KONJ DA DOBIJE NAZIV 'STARI KONJ'?",
    answers: ["5", "3", "7", "10"]
  },
  {
    question: "KOLIKO IMA ATENJANA MEĐU LEGENDARNIH 7 GRČKIH MUDRACA?",
    answers: ["TRI", "DVA", "JEDAN", "ČETIRI"]
  },
  {
    question: "KOLIKO JE DUGAČAK TUNEL UČKA?",
    answers: ["OKO 5 KM", "OKO 3 KM", "OKO 7 KM", "OKO 10 KM"]
  },
  {
  question: "KOJOJ JE DRŽAVI NACISTIČKA NJEMAČKA SLUŽBENO OBJAVILA RAT?",
  answers: ["SAD", "VELIKOJ BRITANIJI", "FRANCUSKOJ", "SSSR-U"]
},
{
  question: "KAKO SE NAZIVA ISLAMSKO VJERSKO PRAVO TEMELJENO NA KURANU?",
  answers: ["ŠERIJAT", "KANON", "TORA", "HALAHA"]
},
{
  question: "KAKO SE ZVAO LEGENDARNI OSNIVAČ CARSTVA INKA?",
  answers: ["MANCO CAPAC", "ATAHUALPA", "HUAYNA CAPAC", "PACHACUTI"]
},
{
  question: "NA KOJEM JE OTOKU BIO ZATVOREN NELSON MANDELA?",
  answers: ["ROBBEN ISLAND", "ALCATRAZ", "DEVIL'S ISLAND", "Rikers Island"]
},
{
  question: "UZ KOJI JE GRAD VEZAN OK CORRAL?",
  answers: ["TOMBSTONE", "DODGE CITY", "EL PASO", "TUCSON"]
},
{
  question: "TKO JE BIO POSLJEDNJI ČOVJEK KOJI JE HODAO PO MJESECU 1972.?",
  answers: ["EUGENE CERNAN", "NEIL ARMSTRONG", "BUZZ ALDRIN", "ALAN SHEPARD"]
},
{
  question: "KOJI JE FARAON IZGRADIO DRUGU PO VELIČINI PIRAMIDU I SFINGU?",
  answers: ["KEFREN", "KEOPS", "MIKERIN", "RAMZES II"]
},
{
  question: "KAKO SE ZVAO KONJ CARA KALIGULE?",
  answers: ["INCITATUS", "BUCEPHALUS", "PEGASUS", "ARION"]
},
{
  question: "NA KOJEM JE OTOČJU UBIJEN JAMES COOK?",
  answers: ["HAWAII", "FIDŽI", "TAHITI", "GALAPAGOS"]
},
{
  question: "KAKO SE ZOVE VALUTA KOSTARIKE?",
  answers: ["COLON", "PESO", "REAL", "SOL"]
},
{
  question: "KOJI JE EUROPSKI NAROD OSNOVAO JOHANNESBURG?",
  answers: ["NIZOZEMCI", "ENGLEZI", "PORTUGALCI", "FRANCUZI"]
},
{
  question: "KOJI JE RAT ZAVRŠIO PADOM SAIGONA 1975.?",
  answers: ["VIJETNAMSKI RAT", "KOREJSKI RAT", "HLADNI RAT", "ZALJEVSKI RAT"]
},
{
  question: "U KOJOJ JE DRŽAVI DJELOVAO POKRET 17. STUDENOG?",
  answers: ["GRČKA", "ITALIJA", "ŠPANJOLSKA", "TURSKA"]
},
{
  question: "KAKO SE NAZIVAJU OKAMENJENI OSTACI RIBA?",
  answers: ["FOSILI", "SEDIMENTI", "MINERALI", "KRISTALI"]
},
{
  question: "KOLIKO JE ZVIJEZDA BILO NA ZASTAVI AMERIČKE KONFEDERACIJE?",
  answers: ["13", "50", "25", "7"]
},
{
  question: "ŠTO PREDSTAVLJA BIJELA BOJA NA FRANCUSKOJ ZASTAVI?",
  answers: ["MONARHIJU", "SLOBODU", "JEDNAKOST", "BRATSTVO"]
},
{
  question: "KOJE JE SVJETSKO ČUDO PRVO UNIŠTENO?",
  answers: ["KOLOS S RODA", "VISEĆI VRTOVI", "MAUZOLEJ U HALIKARNASU", "ARTEMIDIN HRAM"]
},
{
  question: "KOJI JE “ZAČIN” DAO NADIMAK BOJNOM OTROVU DIKLORDIETIL-SULFIDU?",
  answers: ["SENF", "PAPAR", "CIMET", "KURKUMA"]
},
  {
    question: "KOLIKO JE GODINA IMALA LOLITA KAD SE PROFESOR HUMBER HUMBER ZAGLEDAO U NJU?",
    answers: ["12", "14", "10", "16"]
  }
];