const questionBank = [
  {
    question: "IZ KOJE ZEMLJE DOLAZI ANIMIRANI LIK MEDVJEDIĆ PADDINGTON?",
    answers: ["PERUA", "KANADE", "INDIJE", "ISLANDA"]
  },
  {
    question: "KOJI ZNANSTVENIK JE OTKRIO DA JE LJUDSKI VID REZULTAT PROJEKCIJE NA MREŽNICI?",
    answers: ["JOHANNES KEPLER", "KOPERNIK", "ISAAC NEWTON", "GALILEO"]
  },
  {
    question: "KOLIKO DANA PO ISLAMSKOM KALENDARU IMA GODINA KOJA NIJE PRIJESTUPNA?",
    answers: ["354", "365", "376", "400"]
  },
  {
    question: "KOJA MJERNA JEDINICA JE DOBILA IME PO TALIJANSKOM PLEMIĆU?",
    answers: ["VOLT", "PASKAL", "OHM", "HERTZ"]
  },
  {
    question: "KOLIKO JE KILOMETARA ZEMLJA UDALJENA OD SUNCA?",
    answers: ["148.23 MILIJUNA KM", "41.28 MILIJUNA KM", "14.82 MILIJUNA KM", "1.48 MILIJUNA KM"]
  },
  {
    question: "KOLIKO JE LJUDI DO SADA ŽIVJELO NA ZEMLJI?",
    answers: ["OKO 100 MILIJARDI", "OKO 5 BILIJUNA", "OKO 1 BILIJUN", "OKO 50 MILIJARDI"]
  },
  {
    question: "ŠTO JE BIO ČOVJEK NA KOJEM JE TEMELJEN LIK UJAK SAM?",
    answers: ["INSPEKTOR MESA", "POVJESNIČAR", "MEHANIČAR", "POŠTAR"]
  },
  {
    question: "TKO JE DIZAJNIRAO PRVI HELIKOPTER ZA MASOVNU PROIZVODNJU?",
    answers: ["IGOR SIKORSKY", "ELMER SPERRY", "GOTTLIEB DAIMLER", "FERDINAND VON ZEPPELIN"]
  },
  {
    question: "U DRUGOM SVJETSKOM RATU AMERIČKI VOJNICI KORISTILI SU PRVI KOMERCIJALNI SPREJ. KAKAV JE BIO TAJ SPREJ?",
    answers: ["INSEKTICID", "ANTISEPTIK", "TEKUĆINA ZA ČIŠĆENJE", "KREMA ZA BRIJANJE"]
  },
  {
    question: "KOJI AMERIČKI PREDSJEDNIK SE POJAVIO U SERIJI 'LAUGH-IN'?",
    answers: ["RICHARD NIXON", "LYNDON JOHNSON", "JIMMY CARTER", "RONALD REAGAN"]
  },
  {
    question: "KOJI BI VRH NEODOLJIVO PRIVUKAO HARRYJA POTTERA?",
    answers: ["KLEK", "JAPETIĆ", "SLJEME", "SVETA GERA"]
  },
  {
    question: "POLAZAK NARITA, ODREDIŠTE KEFLAVIK – ČIME PUTUJETE?",
    answers: ["AVIONOM", "RAKETOM", "ŽELJEZNICOM", "ŽIČAROM"]
  },
  {
    question: "KOJI JE IMOĆANIN ROĐEN U SPLITU PROSLAVIO PULU?",
    answers: ["MATE PARLOV", "MARIJAN BENEŠ", "ANTUN JOSIPOVIĆ", "ŽELJKO MAVROVIĆ"]
  },
  {
    question: "ASKJA, HEKLA I KATLA IMENA SU ISLANDSKIH...",
    answers: ["VULKANA", "BOŽICA", "GRADOVA", "ZRAČNIH LUKA"]
  },
  {
    question: "KOJI OD KEMIJSKIH ELEMENATA NIJE NAZVAN PO NOBELOVCU?",
    answers: ["AJNŠTAJNIJ", "FERMIJ", "KIRIJ", "NOBELIJ"]
  },
  {
    question: "HENRY MILLER JE ZA OPSCENOST NAPADAN ZBOG SVOJIH:",
    answers: ["OBRATNICA", "POLARNICA", "EKVATORA", "MERIDIJANA"]
  },
  {
    question: "KOJE JE KAZALIŠTE NAJSTARIJE U HRVATSKOJ?",
    answers: ["HVARSKO", "RIJEČKO", "SPLITSKO", "DUBROVAČKO"]
  },
  {
    question: "KAKO SE ZOVE ALBUM DINE DVORNIKA IZ 1993. GODINE?",
    answers: ["PRIRODA I DRUŠTVO", "MATEMATIKA", "ZEMLJOPIS", "TJELESNI ODGOJ"]
  },
  {
    question: "JELEN VRLO RAZGRANATIH ROGOVA U LOVAČKOM ŽARGONU ZOVE SE:",
    answers: ["KAPITALAC", "KAPITALIST", "BURŽUJ", "ARISTOKRAT"]
  },
  {
    question: "KAKO GLASI NARODNI NAZIV ZA VENERU?",
    answers: ["DANICA", "MARICA", "KATICA", "SLAVICA"]
  },
  {
    question: "'LABUĐE JEZERO' P. ILIČA ČAJKOVSKOG JE...",
    answers: ["BALET", "SIMFONIJA", "MJUZIKL", "OPERETA"]
  },
  {
    question: "KOJE ZANIMANJE POVEZUJEMO S IMENOM VARAŽDINCA LJUBOMIRA KEREKEŠA?",
    answers: ["GLUMAC", "NOGOMETAŠ", "POLITIČAR", "ARHITEKT"]
  },
  {
    question: "TKO JE NAKON POSUDBE DUGE 442 GODINE, 20. PROSINCA 1999., MAKAO VRATIO KINI?",
    answers: ["PORTUGALCI", "ENGLEZI", "NIZOZEMCI", "FRANCUZI"]
  },
  {
    question: "ŠTO JE KOD CZESŁAWA MIŁOSZA ZAROBLJENO, A KOD IMMANUELA KANTA ČISTO I PRAKTIČNO?",
    answers: ["UM", "SILA", "ENERGIJA", "ZNANJE"]
  },
  {
    question: "KOJI SISAVAC NESE JAJA?",
    answers: ["ČUDNOVATI KLJUNAŠ", "KOALA", "PLAVETNI KIT", "DUPIN"]
  },
  {
    question: "SAMURAJSKI KODEKS ZOVE SE...",
    answers: ["BUSHIDO", "HARAKIRI", "KENDO", "AIKIDO"]
  },
  {
    question: "GLAGOLSKI OBLICI KOJIMA U HRVATSKOM OZNAČAVAMO PROŠLOST SU PERFEKT, PLUSKVAMPERFEKT, AORIST I...",
    answers: ["IMPERFEKT", "INFINITIV", "IMPERATIV", "INDIKATIV"]
  },
  {
    question: "KOJA LJEPOTICA NAJBOLJE PRISTAJE UZ NOGOMETAŠA ROBERTA KOVAČA?",
    answers: ["ANICA MARTINOVIĆ", "IVA RADIĆ", "FANI ĆAPALIJA", "JELENA MEDIĆ"]
  },
  {
    question: "BACIL JE BAKTERIJA U OBLIKU:",
    answers: ["ŠTAPIĆA", "KUGLICE", "GROZDA", "SPIRALE"]
  },
  {
    question: "KOJI SE OD NAVEDENIH NAZIVA NE ODNOSI NA NAJVIŠI VRH NA ZEMLJI?",
    answers: ["MOLOKAI", "CHOMOLUNGMA", "MOUNT EVEREST", "SAGARMATHA"]
  },
  {
    question: "KAKO SE SLIKOVITO ZOVE ZRAKOPLOV?",
    answers: ["ČELIČNA PTICA", "ZLATNA PTICA", "BAKRENA PTICA", "OLOVNA PTICA"]
  },
  {
    question: "HVATAČ HVATA, BACAČ BACA, UDARAČ UDARA. KOJI JE TO SPORT?",
    answers: ["BEJZBOL", "ODBOJKA", "HOKEJ", "NOGOMET"]
  },
  {
    question: "KOJOJ VRSTI RIJEČI PRIPADA RIJEČ KUTOMJER?",
    answers: ["IMENICA", "GLAGOL", "PRIDJEV", "PRIJEDLOG"]
  },
  {
    question: "KAKO SE ZOVE ŽABAC KOJI PREDVODI MUPPETE?",
    answers: ["KERMIT", "RALF", "GONZO", "WALDORF"]
  },
  {
    question: "'ZDENAC ŽIVOTA' IVANA MEŠTROVIĆA NALAZI SE U ZAGREBU ISPRED:",
    answers: ["KAZALIŠTA", "BURZE", "VIJEĆNICE", "SABORA"]
  },
  {
    question: "LATIĆE CVIJETA ČINE VJENČIĆ, A LAPOVI CVIJETA:",
    answers: ["ČAŠKU", "ČOKOT", "LISKU", "GROZD"]
  },
  {
    question: "TKO SE NATJEČE U KLASI 'OPTIMIST'?",
    answers: ["JEDRILIČARI", "SANJKAŠI", "MOTOCIKLISTI", "BICIKLISTI"]
  },
  {
    question: "RENESANSNI LJETNIKOVAC TVRDALJ NALAZI SE U STAROM GRADU:",
    answers: ["STAROM GRADU", "STARIGRADU", "NOVIGRADU", "BIOGRADU"]
  },
  {
    question: "KOLIKO BAJTOVA IMA 1 KILOBAJT?",
    answers: ["1024", "1000", "1104", "1011"]
  },
  {
    question: "KOJA OD NAVEDENIH ŽIVOTINJA NE SPADA U SKUPINU MORSKIH PASA?",
    answers: ["ORKA", "BIJELA PSINA", "MLAT", "MODRULJ"]
  },
  {
    question: "NA SVOJE PRVO PUTOVANJE KOLUMBO KREĆE:",
    answers: ["1492.", "1496.", "1497.", "1500."]
  },
  {
    question: "ČEŠKI SU EVANGELICI 1618. 'UPRILIČILI' DEFENESTRACIJU, ODNOSNO BACANJE KRALJEVSKOGA NAMJESNIKA:",
    answers: ["KROZ PROZOR", "POD VLAK", "U ŽIVO BLATO", "S MOSTA"]
  },
  {
    question: "KAKO SE JOŠ NA HRVATSKOM KAŽE 'SLIJEPO CRIJEVO'?",
    answers: ["CRVULJAK", "SLJEPIĆ", "VISULJAK", "CRIJEVULJAK"]
  },
  {
    question: "U KOJOJ DRŽAVI ŽIVE KRAŠOVANI?",
    answers: ["U RUMUNJSKOJ", "U MAĐARSKOJ", "U POLJSKOJ", "U UKRAJINI"]
  },
  {
    question: "ŠTO JE PO NARODNOSTI MIKA HAKKINEN?",
    answers: ["FINAC", "ŠKOT", "POLJAK", "DANAC"]
  },
  {
    question: "KOLIKO GODINA TRAJE MANDAT PREDSJEDNIKA HRVATSKE?",
    answers: ["5", "3", "4", "6"]
  },
  {
    question: "GUDAČKI TRIO ČINE VIOLINA, VIOLA I...",
    answers: ["VIOLONČELO", "MANDOLINA", "KONTRABAS", "HARFA"]
  },
  {
    question: "POD KOJIM JE NAZIVOM JAVNOSTI POZNATIJI PLIVIN ANTIBIOTIK AZITHROMYCIN?",
    answers: ["SUMAMED", "ANDOL", "ASPIRIN", "PLIVADON"]
  },
  {
    question: "KOJA JE VELIKAŠKA OBITELJ ČETIRI STOLJEĆA GOSPODARILA TRAKOŠĆANOM?",
    answers: ["DRAŠKOVIĆ", "FRANKOPAN", "ŠUBIĆ", "ERDÖDY"]
  },
  {
    question: "ŠTO JE PO NARODNOSTI ISTRAŽIVAČ FERDINAND MAGELLAN?",
    answers: ["PORTUGALAC", "ŠPANJOLAC", "FRANCUZ", "TALIJAN"]
  },
  {
    question: "UOBIČAJENI NAZIV ZA CESTU OD KARLOVCA DO SENJA JE:",
    answers: ["JOZEFINA", "KAROLINA", "LUJZIJANA", "PAULINA"]
  },
  {
    question: "NEKAD JUŽNA RODEZIJA, A DANAS?",
    answers: ["ZIMBABVE", "KONGO", "UGANDA", "MOZAMBIK"]
  },
  {
    question: "KAKO SE ZOVE GROTESKNI LIK TURSKOG KAZALIŠTA SJENKI I JUNAK ANDRIĆEVE 'PROKLETE AVLIJE'?",
    answers: ["KARAĐOZ", "SIMAN", "DŽEM-SULTAN", "ĐERZELEZ"]
  },
  {
    question: "KOJI JE OD NAVEDENIH NAZIV PUSTINJE, A NE DRŽAVE?",
    answers: ["NAMIB", "GABON", "NIGER", "MALI"]
  },
  {
    question: "TOMAŠ MASARYK BIO JE PREDSJEDNIK:",
    answers: ["ČEHOSLOVAČKE", "POLJSKE", "BUGARSKE", "MAĐARSKE"]
  },
  {
    question: "KAKO JE IME APOLONOVOJ SVEĆENICI IZ DELFA?",
    answers: ["PITIJA", "KIRKA", "IFIGENIJA", "KASANDRA"]
  },
  {
    question: "KOJI JE DRŽIĆEV LIK ZNAN PO ŠKRTOSTI SAKRIVAO TEZORO U ĆUPU?",
    answers: ["SKUP", "POMET", "STANAC", "BOKČILO"]
  },
  {
    question: "KOJI JE NAŠ NAZIV ZA EKVATOR?",
    answers: ["RAVNODNEVNIK", "POLUTNIK", "KOLUTNIK", "PRISOJNIK"]
  },
  {
    question: "IZ KOJE AFRIČKE DRŽAVE DOLAZI KOFI ANNAN, GLAVNI TAJNIK UN-A?",
    answers: ["GANE", "KAMERUNA", "TUNISA", "NIGERIJE"]
  },
  {
    question: "TV SPORTSKA NOVINARKA, OSTVARILA JE USPJEŠNU KARIJERU U:",
    answers: ["ATLETICI", "GIMNASTICI", "UMJETNIČKOM KLIZANJU", "RUKOMETU"]
  },
  {
    question: "FRANCUSKA JE HIMNA POSTALA POPULARNA ZAHVALJUJUĆI DRAGOVOLJCIMA IZ:",
    answers: ["MARSEILLA", "PARIZA", "BORDEAUXA", "STRASBOURA"]
  },
  {
    question: "KAKO NAZIVAMO OŠTAR ZVUK KOJI PROIZVODI JAK VJETAR?",
    answers: ["FIJUK", "CIJUK", "JAUK", "PIJUK"]
  },
  {
    question: "KOGA JE U NASLOVU SVOGA ROMANA MEŠA SELIMOVIĆ SUOČIO SA SMRĆU?",
    answers: ["DERVIŠA", "IMAMA", "MUJEZIMA", "HODŽU"]
  },
  {
    question: "S KOJOM SU PJESMOM 'NOVI FOSILI' NA EUROVIZIJI 1987. OSVOJILI 4. MJESTO?",
    answers: ["JA SAM ZA PLES", "ŽELJO MOJA", "MANGUP", "ROCK ME BABY"]
  },
  {
    question: "AKO JE NAKON 'PSIHA' TRAUMATIČNO POSTALO TUŠIRANJE, NAKON 'MARATONCA' TRAUMATIČAN JE POSTAO ODLAZAK:",
    answers: ["ZUBARU", "MESARU", "FRIZERU", "BANKARU"]
  },
  {
    question: "DOK JE IZRAELCI NISU OKUPIRALI 1967., GOLANSKA VISORAVAN JE BILA U SASTAVU:",
    answers: ["SIRIJE", "EGIPTA", "LIBANONA", "JORDANA"]
  },
  {
    question: "KOJI SE KUKAC LATINSKOG NAZIVA DROSOPHILA MELANOGASTER ČESTO UPOTREBLJAVA U GENETIČKIM POKUSIMA?",
    answers: ["VINSKA MUŠICA", "BOGOMOLJKA", "KRUMPIROVA ZLATICA", "PČELA"]
  },
  {
    question: "KAKO SE ZOVE GLAVNI GRAD UZBEKISTANA?",
    answers: ["TAŠKENT", "BAKU", "SAMARKAND", "MAHAČKALA"]
  },
  {
    question: "NAZIV 'OPEKARNA' ODNOSI SE NA:",
    answers: ["CIGLANU", "PILANU", "DVORANU", "TOPLANU"]
  },
  {
    question: "'IMA JEDNA MODRA RIJEKA, VALJA NAMA...', U PJESMI MAKA DIZDARA.",
    answers: ["PITI", "MLIJEKA", "DO OSJEKA", "PREKO RIJEKE"]
  },
  {
    question: "U FILMSKOM JE SVIJETU KAO 'BB' ZNANA JEDNA I JEDINA...",
    answers: ["BRIGITTE", "BARBARA", "BEATRICE", "BERNADETTE"]
  },
  {
    question: "KAKO U TENISU NAZIVAMO PRIJESTUP PRI IZVOĐENJU SERVISA?",
    answers: ["FOOT FAULT", "BREAK POINT", "POLE POSITION", "TIE BREAK"]
  },
  {
    question: "VUKOTIĆ JE U 'SUROGATU' DUHOVITO PRIKAZAO SUVREMENU CIVILIZACIJU PREPLAVLJENU:",
    answers: ["UMJETNIM TVOREVINAMA", "RATOVIMA", "KISELIM KIŠAMA", "NUKLEARNIM OTPADOM"]
  },
  {
    question: "U ČEMU JE SVJETSKI UGLED STEKAO KORADO KORLEVIĆ?",
    answers: ["ASTRONOMIJI", "BOTANICI", "MEDICINI", "PSIHOLOGIJI"]
  },
  {
    question: "ŠTO SAČINJAVA DOBRE 3/4 ČISTOGA ZRAKA?",
    answers: ["DUŠIK", "KISIK", "UGLJIK", "VODIK"]
  },
  {
    question: "KOJI JE HRVATSKI SPORTAŠ NASTUPIO I NA LJETNIM I NA ZIMSKIM OLIMPIJSKIM IGRAMA?",
    answers: ["IGOR BORASKA", "KREŠIMIR ČULJAK", "IVAN ŠOLA", "VEDRAN PAVLEK"]
  },
  {
    question: "KOJI JE GRAD DO 1966., PRIJE BRUXELLESA, BIO GLAVNO SJEDIŠTE NATO-a?",
    answers: ["PARIZ", "WASHINGTON", "BONN", "MADRID"]
  },
  {
    question: "KOJI JE PIROMAN, ŽELJAN VJEČNE SLAVE, ZAPALIO ARTEMIDIN HRAM U EFEZU?",
    answers: ["HEROSTRAT", "POLIMIK", "NERON", "ETEOKLO"]
  },
  {
    question: "'OLD FAITHFUL' IME JE NAJPOZNATIJEG SVJETSKOG:",
    answers: ["GEJZIRA", "NACIONALNOG PARKA", "VULKANA", "VODOPADA"]
  },
  {
    question: "GLAVNI GRAD BENINA JE:",
    answers: ["PORTO NOVO", "PORTO STARO", "PORTO VISOKO", "PORTO NISKO"]
  },
  {
    question: "KAKO NAZIVAMO GRANICU DVIJU DRŽAVA KOJA SE PROLAZI BEZ VEĆIH FORMALNOSTI?",
    answers: ["MEKA", "SPOREDNA", "PRISTUPAČNA", "TOPLA"]
  },
  {
    question: "KAKO SE ZOVE PRVI STUPANJ U KOMPARACIJI PRIDJEVA?",
    answers: ["POZITIV", "NEGATIV", "ABLATIV", "KOMPARATIV"]
  },
  {
    question: "KAKO JE PREZIME GRGI, CRTANOM LIKU ISMETA VOLJEVICE?",
    answers: ["ČVARAK", "PROTOKOL", "ČOKOLIN", "GRMALJ"]
  },
  {
    question: "NASEOBINU EPIDAUR GRCI SU OSNOVALI NA MJESTU DANAŠNJEG:",
    answers: ["CAVTATA", "VRSARA", "ZADRA", "OMIŠA"]
  },
  {
    question: "KOJI NAROD NE GOVORI GERMANSKIM JEZIKOM?",
    answers: ["FINCI", "DANCI", "ŠVEĐANI", "ISLANĐANI"]
  },
  {
    question: "SVOJEVRSTAN UVOD ZA AMERIČKI GRAĐANSKI RAT BILA JE TZV. BOSTONSKA:",
    answers: ["ČAJANKA", "USPAVANKA", "PIJANKA", "KAJDANKA"]
  },
  {
    question: "NAKON FELINIJEVA FILMA 'SLATKI ŽIVOT' SVIJET JE POSTAO BOGATIJI ZA JEDAN TERMIN:",
    answers: ["PAPARAZZO", "CAPPUCCINO", "CHIAROSCURO", "CALCIO"]
  },
  {
    question: "KOJI SVETAC JE ZAŠTITNIK ENGLESKE?",
    answers: ["SVETI JURAJ", "SVETI JAKOV", "SVETI IVAN", "SVETI ANTON"]
  },
  {
    question: "KOJI JE FRANCUSKI KNJIŽEVNIK AUTOR ROMANA 'ZVONAR CRKVE NOTRE-DAME'?",
    answers: ["VICTOR HUGO", "HONORE DE BALZAC", "GUSTAVE FLAUBERT", "EMILE ZOLA"]
  },
  {
    question: "KAKO JE U NAS PREVEDEN 'DIRTY HARRY', PRVI FILM IZ SERIJALA O PRLJAVOM HARRYJU?",
    answers: ["ŠKORPION UBIJA", "U VRELINI NOĆI", "TEŠKA META", "NA NIŠANU SNAJPERA"]
  },
  {
    question: "KAKO SE NAZIVA SMRTONOSNO ORUŽJE, KIŠOBRAN SA ZAŠILJENIM VRHOM UMOČENIM U OTROV?",
    answers: ["BUGARSKI KIŠOBRAN", "ALBANSKI KIŠOBRAN", "RUMUNJSKI KIŠOBRAN", "NJEMAČKI KIŠOBRAN"]
  },
  {
    question: "KOJE SE BJELGORIČNO DRVO UVUKLO MEĐU CRNOGORIČNO DRVEĆE?",
    answers: ["KESTEN", "SMREKA", "JELA", "TISA"]
  },
  {
    question: "KOJI JE ZNANSTVENIK OTKRIO BACIL TUBERKULOZE?",
    answers: ["ROBERT KOCH", "WILHELM ROENTGEN", "CESARE LOMBROSO", "LOUIS PASTEUR"]
  },
  {
    question: "KAKO SE ZOVE DVOSLOŽNA PJESNIČKA STOPA?",
    answers: ["JAMB", "LIMB", "DITIRAMB", "ROMB"]
  },
  {
    question: "BRDO NA KOJEM SU PRONAĐENI OSTACI KRAPINSKOG PRAČOVJEKA ZOVE SE...",
    answers: ["HUŠNJAKOVO BRDO", "ČEŠNJAKOVO BRDO", "BOŠNJAKOVO BRDO", "LJEŠNJAKOVO BRDO"]
  },
  {
    question: "KAKO SE ZOVE VLASNICA HALJINE O KOJOJ SE 1998. BRUJILO U CIJELOM WASHINGTONU?",
    answers: ["MONICA LEWINSKY", "VENUS WILLIAMS", "MADONNA", "JENNIFER LOPEZ"]
  },
  {
    question: "KAKO SE ZOVE NAJGUŠĆI DIO ATMOSFERE U KOJEM SE ZBIVAJU METEOROLOŠKE PROMJENE?",
    answers: ["TROPOSFERA", "EGZOSFERA", "NANOSFERA", "TERMOSFERA"]
  },
  {
    question: "KOJA JE ŽLIJEZDA ČOVJEČJEG ORGANIZMA NAJVEĆA?",
    answers: ["JETRA", "ŠTITNJAČA", "GUŠTERAČA", "HIPOFIZA"]
  },
  {
    question: "KOJI JE RIMLJANIN PRVI POČEO MJERITI PULS U DIJAGNOSTIČKE SVRHE?",
    answers: ["GALEN", "JUVENAL", "PLAUT", "PLUTARH"]
  },
  {
    question: "ŠTO U DOSLOVNOM PRIJEVODU ZNAČI GALICIZAM ŠOFER?",
    answers: ["LOŽAČ", "PUTNIK", "CESTA", "VOZAČ"]
  },
  {
    question: "NAJPOZNATIJA SLIKA EDVARDA MUNCHA JEST:",
    answers: ["KRIK", "GRČ", "SAN", "UZDAH"]
  },
  {
    question: "NA KOLIKO KOTAČA POBJEĐUJE LANCE ARMSTRONG?",
    answers: ["2", "8", "4", "3"]
  },
  {
    question: "RENEOVA SUPRUGA U SERIJI 'ALO, ALO' ZOVE SE:",
    answers: ["EDITTE", "HELGA", "MICHELLE", "YVETTE"]
  },
  {
    question: "KOJE JE MJESTO RODNO MJESTO TINA UJEVIĆA?",
    answers: ["VRGORAC", "RASTUŠJE", "DRINOVCI", "LUKOVDOL"]
  },
  {
    question: "KOJI OD NAVEDENIH PLESOVA NE POTJEČE S KUBE?",
    answers: ["SAMBA", "MAMBO", "RUMBA", "SALSA"]
  },
  {
    question: "TKO SE SUKOBIO U STOGODIŠNJEM RATU?",
    answers: ["FRANCUSKA I ENGLESKA", "ŠPANJOLSKA I FRANCUSKA", "ENGLESKA I NJEMAČKA", "NJEMAČKA I RUSIJA"]
  },
  {
    question: "BOŽICA AFRODITA RODILA SE IZ...",
    answers: ["MORSKE PJENE", "VATRE", "KORALJA", "RUŽE"]
  },
  {
    question: "KOLIKO NOGU IMA MRAV?",
    answers: ["6", "4", "10", "8"]
  },
  {
    question: "KOJA JE DAMA POSTALA PRVA MINISTRICA U HRVATSKOJ VLADI?",
    answers: ["LJILJA VOKIĆ", "LJERKA MINTAS-HODAK", "VESNA GIRARDI-JURKIĆ", "NANSI IVANIŠEVIĆ"]
  },
  {
    question: "KOJI REFLEKS LIJEČNIK PROVJERAVA UDARCEM U KOLJENO?",
    answers: ["PATELARNI", "LUMBALNI", "ABDOMINALNI", "DENTALNI"]
  },
  {
    question: "NAJSJEVERNIJA TOČKA EUROPE NALAZI SE U FINNMARKU:",
    answers: ["U NORVEŠKOJ", "U ŠVEDSKOJ", "U FINSKOJ", "U DANSKOJ"]
  },
  {
    question: "KAKO SE ZOVE NAJVEĆI OD 7000 FILIPINSKIH OTOKA?",
    answers: ["LUZON", "MINDANAO", "PALAWAN", "CEBU"]
  },
  {
    question: "KAKO SE ZOVE NASTAMBA SJEVERNOAMERIČKIH INDIJANACA?",
    answers: ["TIPI", "IGLU", "JURTA", "KOLIBA"]
  },
  {
    question: "KAKO SE ZOVE NOVČIĆ KOJIM SU GRCI PLAĆALI PRIJEVOZ PREKO STIKSA U HAD?",
    answers: ["OBOL", "DENAR", "TALENT", "DRAHMA"]
  },
  {
    question: "KAKO SE ZOVE OBIČAJNO PRAVO U ISLAMSKIH NARODA?",
    answers: ["ADAT", "ŠERIJAT", "SUNNA", "FETVA"]
  },
  {
    question: "KAKO SE ZOVE LIK KOJEG JE U 'DINASTIJI' GLUMILA LINDA EVANS?",
    answers: ["KRYSTLE CARRINGTON", "ALEXIS COLBY", "FALLON CARRINGTON", "DOMINIQUE DEVERAUX"]
  },
  {
    question: "KAKO SE ZOVE MAJKA BENJAMINA, 12. SINA JAKOVLJEVA, KOJA JE UMRLA PRI PORODU?",
    answers: ["RAHELA", "LEA", "SARA", "REBEKA"]
  },
  {
    question: "KAKO SE ZOVE MITOLOŠKO ČUDOVIŠTE U KOJEM SU SJEDINJENI LAV I ORAO?",
    answers: ["GRIFON", "KENTAUR", "MINOTAUR", "SFINGA"]
  },
  {
    question: "KOLIKO JE KAVALIRA IMALA KRLEŽINA GOSPOĐICA MELANIJA?",
    answers: ["TRI", "DVA", "PET", "JEDAN"]
  },
  {
    question: "KOLIKO JE MAĆEHA IMALA BLOODY MARY, ENGLESKA KRALJICA MARIJA TUDOR?",
    answers: ["DVIJE", "TRI", "JEDNU", "ČETIRI"]
  },
  {
    question: "KOME LIJEČNICI POLAŽU ZAKLETVU DA ĆE SAVJESNO I DOSTOJNO OBAVLJATI SVOJU DUŽNOST?",
    answers: ["HIPOKRATU", "GALENU", "ASKLEPIJU", "PLATONU"]
  },
  {
    question: "KOME SE DOGODILO UKAZANJE U LOURDESU?",
    answers: ["BERNADETTI SOUBIROUS", "IVANI ORLEANKI", "KATARINI SIENSKOJ", "TEREZI AVILSKOJ"]
  },
  {
    question: "KORDELIJA, REGAN I GOMERIL KĆERI SU KOJEG KRALJA?",
    answers: ["LEARA", "HAMLETA", "RICHARDA III", "MACBETHA"]
  },
  {
    question: "KAKO SE ZOVE KRAĆA SKLADBA NESTALNA OBLIKA, NAJČEŠĆE ZA KLAVIR?",
    answers: ["IMPROMPTU", "SONATA", "ETIDA", "SIMFONIJA"]
  },
  {
    question: "KOJU SU FRANCUSKU KRALJICU ZVALI 'UDOVICA CAPET'?",
    answers: ["MARIJA ANTOANETA", "MARIJA MEDICI", "KATARINA MEDICI", "ELEONORA AKVITANSKA"]
  },
  {
    question: "KOJA ŽIVOTINJA JE NAJČEŠĆE PRIKAZIVANA U MINOJSKOJ UMJETNOSTI NA KRETI?",
    answers: ["BIK", "KONJ", "LAV", "KOZA"]
  },
  {
    question: "KOLIKI JE ZBROJ SVIH KUTOVA U TROKUTU?",
    answers: ["180°", "360°", "90°", "270°"]
  },
  {
    question: "KOLIKO GODINA MORA NAVRŠITI KONJ DA DOBIJE NAZIV 'STARI KONJ'?",
    answers: ["5", "3", "7", "10"]
  },
  {
    question: "KOLIKO IMA ATENJANA MEĐU LEGENDARNIH 7 GRČKIH MUDRACA?",
    answers: ["TRI", "DVA", "JEDAN", "ČETIRI"]
  },
  {
    question: "KOLIKO JE DUGAČAK TUNEL UČKA?",
    answers: ["OKO 5 KM", "OKO 3 KM", "OKO 7 KM", "OKO 10 KM"]
  },
  {
    question: "KOLIKO JE GODINA IMALA LOLITA KAD SE PROFESOR HUMBER HUMBER ZAGLEDAO U NJU?",
    answers: ["12", "14", "10", "16"]
  }
];